import {describe,expect,it} from 'vitest'
import type {HistoricalPrice,StockSnapshot} from '../types'
import {buildStockAnalysis,calculatePriceZones,clusterTolerance,explainTrendForUser,median,opportunityInterpretation,trendAnalysis,volumeProfilePrice,volumeStatistics} from './stockAnalysis'

const history=(count=240,start=100,step=.2,volume=1000):HistoricalPrice[]=>Array.from({length:count},(_,index)=>{const close=start+index*step,date=new Date(Date.UTC(2025,0,2+index));return{date:date.toISOString().slice(0,10),open:close-.5,high:close+1,low:close-1,close,adjustedClose:close,volume:index===count-1?volume*1.6:volume}})
const stock=(prices=history()):StockSnapshot=>{const price=prices.at(-1)?.close??null;return{ticker:'TEST',company:'Test',sector:'Tech',marketCap:null,pe:20,eps:5,price,changePercent:.01,ath:null,high52:price?price*1.1:null,drawdown52:-.09,low52:price?price*.75:null,atl:null,mdd:{2024:-.2,2025:-.25,2026:-.18},yearOpen:100,ytdReturn:.2,return1m:.02,return3m:.05,return6m:.1,return1y:.2,return3y:null,return5y:null,ma20:price?price-2:null,ma60:price?price-4:null,ma120:price?price-8:null,ma200:price?price-12:null,historyComplete:false,priceHistory:prices,dataSource:'toss',priceStability:'안정',fundamentalsHistory:[]}}

describe('stock technical analysis',()=>{
  it('detects all MA above with increased rising volume',()=>{const result=buildStockAnalysis(stock(),[stock()]);expect(result.trend).toMatch(/상승/);expect(result.volumeState).toBe('거래 집중');expect(result.priceVolumeState).toContain('가격 상승')})
  it('detects all MA below with falling direction',()=>{const prices=history(240,200,-.3,1000);prices.at(-1)!.volume=1800;const result=trendAnalysis(prices,prices.at(-1)!.close);expect(result.trend).toMatch(/하락/)})
  it('detects short recovery above MA20 and MA60',()=>{const result=trendAnalysis(history(),147.8);expect(result.ma.ma20.difference).not.toBeNull();expect(result.trend).toMatch(/상승|방향/)})
  it('classifies ordered and reverse ordered MA arrays',()=>{expect(trendAnalysis(history(),200).arrangement).toBe('정배열');expect(trendAnalysis(history(240,200,-.2),100).arrangement).toBe('역배열')})
  it('does not calculate volume strength under 20 prior days',()=>expect(volumeStatistics(history(20)).ratio).toBeNull())
  it('excludes negative EPS from data completeness',()=>{const sample=stock();sample.eps=-1;expect(buildStockAnalysis(sample,[sample]).missing.some(item=>item.includes('EPS'))).toBe(true)})
  it('reports insufficient 52 week data',()=>{const sample=stock(history(100));sample.return1y=null;expect(buildStockAnalysis(sample,[sample]).missing).toContain('52주 데이터 부족')})
  it('recognizes a buy interest zone',()=>{const sample=stock();sample.ma120=120;sample.ma200=121;sample.low52=119;sample.price=125;expect(calculatePriceZones(sample).buyZone).not.toBeNull()})
  it('describes a downside break below a buy zone',()=>{const sample=stock();sample.price=110;sample.low52=119;sample.high52=150;sample.mdd={2024:-.2,2025:-.2,2026:-.2};sample.ma60=null;sample.ma120=null;sample.ma200=null;expect(calculatePriceZones(sample).buyZone?.relation).toContain('하향 이탈')})
  it('recognizes an approaching profit management zone',()=>{const sample=stock();sample.price=140;sample.high52=150;sample.ath=151;expect(calculatePriceZones(sample).sellZone).not.toBeNull()})
  it('strengthens a resistance break when volume expands',()=>{const prices=history();prices.at(-1)!.volume=1800;expect(buildStockAnalysis(stock(prices),[stock(prices)]).priceVolumeState).toContain('거래량 증가')})
  it('labels analysis limits when buy and sell zones overlap',()=>{const sample=stock();sample.price=125;sample.low52=123;sample.ma120=125.5;sample.high52=126;sample.ath=127;const zones=calculatePriceZones(sample);expect(zones.buyZone?.status).toContain('판단 제한');expect(zones.sellZone?.status).toContain('판단 제한')})
  it('shows a low-confidence zone from one usable reference',()=>{const sample=stock();sample.price=110;sample.low52=80;sample.ma60=null;sample.ma120=null;sample.ma200=null;sample.mdd={};const zone=calculatePriceZones(sample).buyZone;expect(zone).not.toBeNull();expect(zone?.status).toContain('신뢰도 낮음')})
  it('uses the arithmetic median for an even MDD set',()=>expect(median([.2,.3,.4,.5])).toBeCloseTo(.35))
  it('deduplicates a shared 60-day and 52-week low event for confidence',()=>{const sample=stock();const recentLow=Math.min(...sample.priceHistory.slice(-60).map(point=>point.low!));sample.low52=recentLow*.999;sample.ma60=recentLow*1.002;sample.ma120=recentLow*1.004;const zone=calculatePriceZones(sample).buyZone;expect(zone?.reasons.filter(reason=>reason.duplicateGroup==='동일 저점 사건')).toHaveLength(2)})
  it('deduplicates a shared swing and 52-week high event',()=>{const sample=stock();const recentHigh=Math.max(...sample.priceHistory.slice(-60).map(point=>point.high!));sample.high52=recentHigh*1.001;sample.ath=recentHigh*1.003;const zone=calculatePriceZones(sample).sellZone;expect(zone?.reasons.filter(reason=>reason.duplicateGroup==='동일 고점 사건')).toHaveLength(2)})
  it('keeps MA60 MA120 and MA200 independent and adds a dense-MA bonus',()=>{const sample=stock();sample.price=130;sample.ma60=120;sample.ma120=121;sample.ma200=122;sample.low52=80;sample.mdd={};const zone=calculatePriceZones(sample).buyZone;expect(zone?.reasons.filter(reason=>reason.name.startsWith('MA')).map(reason=>reason.name)).toEqual(['MA60','MA120','MA200']);expect(zone?.maCluster).toBe(true)})
  it('does not let a synthetic MDD price alone create high confidence',()=>{const sample=stock();sample.low52=null;sample.ma60=null;sample.ma120=null;sample.ma200=null;sample.mdd={2024:-.2,2025:-.2};const zone=calculatePriceZones(sample).buyZone;expect(zone?.confidence).toBeLessThan(65)})
  it('keeps ATR tolerance clamped and falls back to three percent',()=>{expect(clusterTolerance(null,100)).toBe(.03);expect(clusterTolerance(1,100)).toBe(.015);expect(clusterTolerance(20,100)).toBe(.08)})
  it('detects a daily volume concentration price',()=>{const prices=history(80);for(const point of prices.slice(20,60)){point.close=120;point.adjustedClose=120;point.high=121;point.low=119;point.volume=10000}expect(volumeProfilePrice(prices)).toBeGreaterThan(118);expect(volumeProfilePrice(prices)).toBeLessThan(122)})
  it('reports repeated support reactions',()=>{const prices=history(100,100,0);for(let i=20;i<90;i+=15){prices[i].close=100;prices[i].adjustedClose=100;prices[i].low=99;for(let j=1;j<=5;j++){prices[i+j].close=104;prices[i+j].adjustedClose=104}}const sample=stock(prices);sample.price=104;sample.low52=100;sample.ma60=100;sample.ma120=null;sample.ma200=null;const zone=calculatePriceZones(sample).buyZone;expect(zone?.reaction.tests).toBeGreaterThan(0);expect(zone?.reaction.successes).toBeGreaterThan(0)})
  it('reports repeated resistance reactions',()=>{const prices=history(100,96,0);for(let i=20;i<90;i+=15){prices[i].close=100;prices[i].adjustedClose=100;prices[i].high=101;for(let j=1;j<=5;j++){prices[i+j].close=96;prices[i+j].adjustedClose=96}}const sample=stock(prices);sample.price=96;sample.high52=100;sample.ath=101;sample.ma60=null;sample.ma120=null;sample.ma200=null;const zone=calculatePriceZones(sample).sellZone;expect(zone?.reaction.tests).toBeGreaterThan(0);expect(zone?.reaction.successes).toBeGreaterThan(0)})
  it('normalizes confidence when optional evidence is unavailable',()=>{const sample=stock(history(40));sample.ma60=null;sample.ma120=null;sample.ma200=null;const zone=calculatePriceZones(sample).buyZone;expect(zone?.confidenceCompleteness).toBeLessThan(100);expect(zone?.confidence).toBeGreaterThanOrEqual(0)})
  it('does not use a holding average cost in objective zones',()=>{const sample=stock() as StockSnapshot&{averageCost?:number};sample.averageCost=10;const first=calculatePriceZones(sample);sample.averageCost=1000;expect(calculatePriceZones(sample)).toEqual(first)})
  it('reproduces an as-of zone without looking at later prices',()=>{const base=history(220),cutoff=base[199].date,sample=stock(base),first=calculatePriceZones(sample,cutoff);const future=[...base,...history(20,500,2).map((point,index)=>({...point,date:new Date(Date.UTC(2026,0,2+index)).toISOString().slice(0,10)}))];expect(calculatePriceZones(stock(future),cutoff)).toEqual(first)})
  it('uses requested opportunity interpretation bands',()=>{expect(opportunityInterpretation(79).label).toBe('관찰 우선');expect(opportunityInterpretation(45).label).toBe('일부 충족');expect(opportunityInterpretation(20).label).toBe('매력 제한')})
  it('explains mixed weak trends in plain language with a next check',()=>{const result=explainTrendForUser('약세 우세','혼조 배열','관심 감소');expect(result.plainTrendMeaning).toContain('오늘 가격이 올랐더라도');expect(result.arrangementMeaning).toContain('서로 다른 방향');expect(result.nextTrendCheck).toContain('MA20')})
})
