import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'

const source=JSON.parse(readFileSync('backtest/results/phase4_2-full.json','utf8'))
const histories=source.histories,tickers=['NVDA','AAPL','GOOG','MSFT','AMZN','AVGO','META','TSLA'],TEST_START='2016-01-01',TEST_END='2025-12-31'
const valid=value=>typeof value==='number'&&Number.isFinite(value),avg=xs=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null,median=xs=>{const a=[...xs].filter(valid).sort((a,b)=>a-b);return!a.length?null:a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2},clamp=(x,a,b)=>Math.max(a,Math.min(b,x))
const ma=(p,n)=>p.length<n?null:avg(p.slice(-n).map(x=>x.close)),atr=p=>{const q=p.slice(-15);return q.length<15?null:avg(q.slice(1).map((x,i)=>Math.max(x.high-x.low,Math.abs(x.high-q[i].close),Math.abs(x.low-q[i].close))))}
const annualMdd=(p,y)=>{let peak=-Infinity,mdd=0;for(const x of p)if(x.date.startsWith(String(y))){peak=Math.max(peak,x.close);mdd=Math.min(mdd,x.close/peak-1)}return peak===-Infinity?null:mdd}
const mddRef=p=>{const y=Number(p.at(-1).date.slice(0,4));return median([y-4,y-3,y-2,y-1,y].map(v=>annualMdd(p,v)).filter(valid).map(Math.abs))}
const slopeState=value=>value>.005?'상승':value<-.005?'하락':'평탄'
const maInfo=(p,n)=>{const value=ma(p,n),prior=ma(p.slice(0,-10),n),slope=valid(value)&&valid(prior)&&prior!==0?value/prior-1:null;return{value,slope,state:valid(slope)?slopeState(slope):null}}
const stability=(p,a,b)=>{if(p.length<25||!valid(a)||!valid(b))return 0;const price=p.at(-1).close,recent=Math.min(...p.slice(-5).map(x=>x.low)),prior=Math.min(...p.slice(-25,-5).map(x=>x.low));if(recent<=prior&&price<a&&a<b)return 0;if(price>=a&&a>=b)return 15;if(price>=a)return 11;return 5}

function scores(){const byDate=new Map(),out=new Map();for(const ticker of tickers){const points=histories[ticker];for(let i=251;i<points.length;i++){const p=points.slice(0,i+1),day=p.at(-1);if(day.date<TEST_START||day.date>TEST_END)continue;const high=Math.max(...p.slice(-252).map(x=>x.high)),dd=day.close/high-1,ref=mddRef(p),row={ticker,date:day.date,mdd:ref?30*clamp(Math.abs(dd)/ref,0,1):0,stability:stability(p,ma(p,20),ma(p,60)),dd};const rows=byDate.get(day.date)??[];rows.push(row);byDate.set(day.date,rows)}}for(const rows of byDate.values()){const ranked=[...rows].sort((a,b)=>a.dd-b.dd);for(const row of rows){const rank=ranked.findIndex(x=>x.ticker===row.ticker),relative=20*(ranked.length-1-rank)/(ranked.length-1);out.set(`${row.ticker}|${row.date}`,Math.round((row.mdd+relative+row.stability)/65*100))}}return out}

function zone(p,type,mode){const last=p.at(-1);if(!last||p.length<252)return null;const current=last.close,recent=p.slice(-60),year=p.slice(-252),reference=mddRef(p),mas=[60,120,200].map(n=>({name:`ma${n}`,...maInfo(p,n)})),tol=clamp((atr(p)??current*.03)/current*1.25,.015,.08)
  const raw=type==='buy'?[['swing60',Math.min(...recent.map(x=>x.low)),null],['low52',Math.min(...year.map(x=>x.low)),null],['mdd',reference?Math.max(...year.map(x=>x.high))*(1-reference):null],...mas.map(x=>[x.name,x.value,x])]:[['swing60',Math.max(...recent.map(x=>x.high)),null],['high52',Math.max(...year.map(x=>x.high)),null],['ath',Math.max(...p.map(x=>x.close)),null],...mas.map(x=>[x.name,valid(x.value)&&x.value>current?x.value:null,x])]
  let items=raw.filter(([,price])=>valid(price)).filter(([name,price])=>!(type==='buy'&&name.startsWith('ma')&&price>current)).map(([name,price,detail])=>({name,price,slope:detail?.slope??null,slopeState:detail?.state??null}))
  if(type==='buy'&&mode==='hard')items=items.filter(x=>!x.name.startsWith('ma')||x.slopeState!=='하락');if(!items.length)return null
  let candidates=[];for(const item of items){const group=items.filter(x=>Math.abs(x.price-item.price)/current<=tol);if(group.length>candidates.length)candidates=group}if(candidates.length<2){const eligible=items.filter(x=>type==='buy'?x.price<=current*1.15:x.price>=current*.85);candidates=[[...(eligible.length?eligible:items)].sort((a,b)=>Math.abs(a.price-current)-Math.abs(b.price-current))[0]]}
  const make=xs=>{const values=xs.map(x=>x.price),mid=median(values);return{low:Math.min(...values),high:Math.max(...values),mid,width:(Math.max(...values)-Math.min(...values))/mid}}
  const original=make(candidates),outlier=candidates.length>=3?[...candidates].sort((a,b)=>Math.abs(b.price-original.mid)-Math.abs(a.price-original.mid))[0]:null,trimmed=original.width>=.05&&candidates.length>=3&&!!outlier,finalCandidates=trimmed?candidates.filter(x=>x!==outlier):candidates
  return{...make(finalCandidates),candidates,finalCandidates,trimmed,outlier:trimmed?outlier:null,current}
}

const mddCurve=curve=>{let peak=-Infinity,mdd=0;for(const x of curve){peak=Math.max(peak,x.value);mdd=Math.min(mdd,x.value/peak-1)}return mdd}
const mergeCurves=curves=>{const dates=[...new Set(curves.flatMap(x=>x.map(y=>y.date)))].sort();return dates.map(date=>({date,value:avg(curves.map(curve=>[...curve].reverse().find(x=>x.date<=date)?.value??1))}))}
function metric(trades,curve){const closed=trades.filter(x=>x.closed),net=closed.map(x=>x.net);return{entries:trades.length,closed:closed.length,targetRate:trades.length?closed.length/trades.length:null,medianReturn:median(net),meanReturn:avg(net),cumulative:curve.length?curve.at(-1).value/curve[0].value-1:null,equityMdd:mddCurve(curve),meanMae:avg(trades.map(x=>x.mae)),medianMae:median(trades.map(x=>x.mae)),meanMfe:avg(trades.map(x=>x.mfe)),medianMfe:median(trades.map(x=>x.mfe)),medianDays:median(closed.map(x=>x.days)),openRate:trades.length?(trades.length-closed.length)/trades.length:null}}
function simulate(mode,scoreMap){const all=[],curves={},perTicker=[];for(const ticker of tickers){const points=histories[ticker],trades=[],curve=[];let cash=1,shares=0,position=null;for(let i=251;i<points.length;i++){const day=points[i];if(day.date<TEST_START||day.date>TEST_END)continue;const p=points.slice(0,i+1);if(!position){const buy=zone(p,'buy',mode),sell=zone(p,'sell',mode),score=scoreMap.get(`${ticker}|${day.date}`);if(score>=70&&buy&&sell&&sell.mid>buy.mid&&day.low<=buy.high&&day.high>=buy.low){shares=cash*.9995/buy.mid;cash=0;position={ticker,entryDate:day.date,entryIndex:i,entry:buy.mid,target:sell.mid,low:day.low,high:day.high,candidates:buy.finalCandidates,buy}}}else{position.low=Math.min(position.low,day.low);position.high=Math.max(position.high,day.high);if(i>position.entryIndex&&day.high>=position.target){cash=shares*position.target*.9995;trades.push({...position,closed:true,exitDate:day.date,days:i-position.entryIndex,net:position.target/position.entry*.999**1-1,mae:Math.min(0,position.low/position.entry-1),mfe:position.high/position.entry-1});shares=0;position=null}}curve.push({date:day.date,value:cash+shares*day.close})}if(position){const last=curve.at(-1);trades.push({...position,closed:false,exitDate:last.date,days:points.findIndex(x=>x.date===last.date)-position.entryIndex,net:last.value-1,mae:Math.min(0,position.low/position.entry-1),mfe:position.high/position.entry-1})}curves[ticker]=curve;all.push(...trades);perTicker.push({ticker,...metric(trades,curve)})}const curve=mergeCurves(Object.values(curves));return{trades:all,curves,curve,perTicker,summary:metric(all,curve)}}
function structure(mode){const rows=[];for(const ticker of tickers){const points=histories[ticker];for(let i=251;i<points.length;i++){const day=points[i];if(day.date<TEST_START||day.date>TEST_END)continue;const p=points.slice(0,i+1),buy=zone(p,'buy',mode),sell=zone(p,'sell',mode);if(buy&&sell)rows.push({ticker,date:day.date,buy,sell,current:day.close})}}const buy=rows.map(x=>x.buy);return{rows,summary:{zones:rows.length,buyMeanWidth:avg(buy.map(x=>x.width)),buyMedianWidth:median(buy.map(x=>x.width)),overlapRate:rows.length?rows.filter(x=>x.buy.high>=x.sell.low).length/rows.length:null,buyAboveCurrentRate:rows.length?rows.filter(x=>x.buy.high>x.current).length/rows.length:null,trimApplied:buy.filter(x=>x.trimmed).length,ma60Included:buy.filter(x=>x.finalCandidates.some(c=>c.name==='ma60')).length,ma120Included:buy.filter(x=>x.finalCandidates.some(c=>c.name==='ma120')).length,ma200Included:buy.filter(x=>x.finalCandidates.some(c=>c.name==='ma200')).length}}}
const groupMetric=(trades,test)=>{
  const selected=trades.filter(test)
  const curves=tickers.map(ticker=>{
    const own=selected.filter(x=>x.ticker===ticker)
    if(!own.length)return []
    const closed=own.filter(x=>x.closed)
    return [{date:own[0].entryDate,value:1},...closed.map((x,index)=>({
      date:x.exitDate,
      value:own.slice(0,index+1).reduce((value,trade)=>value*(1+trade.net),1),
    }))]
  }).filter(curve=>curve.length)
  return metric(selected,mergeCurves(curves))
}
const periodOf=date=>date<='2019-12-31'?'2016~2019':date<='2021-12-31'?'2020~2021':date<='2022-12-31'?'2022':'2023~2025'
const scoreMap=scores(),baseline=simulate('baseline',scoreMap),soft=simulate('soft',scoreMap),hard=simulate('hard',scoreMap),baseStructure=structure('baseline'),hardStructure=structure('hard')
const has=(trade,state,name=null)=>trade.candidates.some(c=>c.name.startsWith('ma')&&c.slopeState===state&&(!name||c.name===name))
const groups=[['상승 MA 포함',x=>has(x,'상승')],['평탄 MA 포함',x=>has(x,'평탄')],['하락 MA 포함',x=>has(x,'하락')],['MA 미포함',x=>!x.candidates.some(c=>c.name.startsWith('ma'))],['하락 MA 미포함',x=>!has(x,'하락')]].map(([label,test])=>({label,...groupMetric(baseline.trades,test)}))
const periods=['ma60','ma120','ma200'].flatMap(name=>['상승','평탄','하락'].map(state=>({ma:name.toUpperCase(),state,...groupMetric(baseline.trades,x=>has(x,state,name))})))
const periodRows=['2016~2019','2020~2021','2022','2023~2025'].flatMap(period=>['baseline','hard'].map(mode=>{const sim=mode==='baseline'?baseline:hard;return{period,mode,...metric(sim.trades.filter(x=>periodOf(x.entryDate)===period),sim.curve.filter(x=>periodOf(x.date)===period)),fallingRate:(sim.trades.filter(x=>periodOf(x.entryDate)===period&&has(x,'하락')).length/Math.max(1,sim.trades.filter(x=>periodOf(x.entryDate)===period).length))}}))
const perTicker=tickers.flatMap(ticker=>['baseline','hard'].map(mode=>{const sim=mode==='baseline'?baseline:hard,trade=sim.trades.filter(x=>x.ticker===ticker);return{ticker,mode,...metric(trade,sim.curves[ticker]),fallingEntries:trade.filter(x=>has(x,'하락')).length}}))
const leaveOneOut=tickers.flatMap(excluded=>['baseline','hard'].map(mode=>{const sim=mode==='baseline'?baseline:hard,curve=mergeCurves(Object.entries(sim.curves).filter(([ticker])=>ticker!==excluded).map(([,value])=>value));return{excluded,mode,...metric(sim.trades.filter(x=>x.ticker!==excluded),curve)}}))
const hardKeys=new Set(hard.trades.map(x=>`${x.ticker}|${x.entryDate}`)),lost=baseline.trades.filter(x=>!hardKeys.has(`${x.ticker}|${x.entryDate}`)),maintained=baseStructure.rows.filter((row,index)=>row.buy.finalCandidates.some(c=>c.name.startsWith('ma')&&c.slopeState==='하락')&&Math.abs(row.buy.mid-hardStructure.rows[index].buy.mid)/row.buy.mid<.000001).length,midChange=avg(baseStructure.rows.map((row,index)=>Math.abs(row.buy.mid-hardStructure.rows[index].buy.mid)/row.buy.mid))
const falling=groups.find(x=>x.label==='하락 MA 포함'),nonFalling=groups.find(x=>x.label==='하락 MA 미포함'),hardRiskBetter=hard.summary.meanMae>baseline.summary.meanMae+.01&&hard.summary.equityMdd>=baseline.summary.equityMdd+.01,verdict=falling.entries>=10&&hardRiskBetter?'A. 운영 반영 권장':falling.entries>=10?'B. 추가 검증 필요':'C. 운영 반영 보류'
const conclusion=`${verdict} · 10년에서 하락 MA 포함 진입은 ${falling.entries}건입니다. Hard slope는 하락 중인 매수 MA만 제외했으며, 수익·위험 지표의 동시 개선 여부를 기준으로 판단했습니다. 운영 알고리즘은 변경하지 않았습니다.`
const date=new Date().toISOString().slice(0,10),runId=`phase4-3-${date}`,comparison=[['Baseline',{structure:baseStructure.summary,performance:baseline.summary}],['Soft',{structure:baseStructure.summary,performance:soft.summary}],['Hard',{structure:hardStructure.summary,performance:hard.summary}]].map(([mode,value])=>({mode,...value.structure,...value.performance}))
const sections=[['comparison','Baseline / Soft / Hard',comparison],['falling','하락 MA 표본',[{all:falling.entries,nonFalling:nonFalling.entries,ma60:periods.find(x=>x.ma==='MA60'&&x.state==='하락').entries,ma120:periods.find(x=>x.ma==='MA120'&&x.state==='하락').entries,ma200:periods.find(x=>x.ma==='MA200'&&x.state==='하락').entries}]],['period-ma','MA 기간별',periods],['bear','2022 약세구간',periodRows.filter(x=>x.period==='2022')],['period','기간별',periodRows],['ticker','종목별',perTicker],['loo','Leave-One-Stock-Out',leaveOneOut],['structure','가격대 구조 변화',[{baseline:baseStructure.summary,hard:hardStructure.summary,meanMidpointChange:midChange,lostEntries:lost.length,fallingMaZoneMaintained:maintained}]],['conclusion','최종 판정',[{label:'판정',value:verdict},{label:'운영 변경',value:'0건 · 결과 보고 후 결정'},{label:'근거',value:conclusion}]]].map(([id,title,rows],sortOrder)=>({id,parentId:null,sectionType:'report',title,summary:'4.2 동일 10년 TOSS 스냅샷 · slope 단일 변수 · Fixed 차익관리',reportData:{rows},sortOrder:sortOrder+1}))
const run={id:runId,runDate:date,phase:'4.3차 · MA slope 10년 재검증',title:'MA slope 10년 유효성 재검증',algorithmVersion:'BT-v4.3',periodStart:TEST_START,periodEnd:TEST_END,universe:'TOSS 8종목 · 4.2 동일 스냅샷',config:{scoreThreshold:70,weights:'30/20/15',maDirection:true,atrMultiplier:1.25,minTolerance:.015,atrCap:.08,zone:'min~max',trim:'폭>=5% · 후보>=3 · outlier 1개 제거',slope:'10거래일 · 상승 > +0.5%, 평탄 ±0.5%, 하락 < -0.5%',fixedTarget:'entry-day sell midpoint',diagnosticOnly:true},summary:{baseline:{structure:baseStructure.summary,performance:baseline.summary},soft:{structure:baseStructure.summary,performance:soft.summary},hard:{structure:hardStructure.summary,performance:hard.summary},groups,periods,periodRows,perTicker,leaveOneOut,structureChange:{midChange,lostEntries:lost.length,maintained},verdict},conclusion,createdAt:new Date().toISOString(),sections}
mkdirSync('backtest/results',{recursive:true});writeFileSync('backtest/results/phase4_3-summary.json',JSON.stringify(run,null,2));writeFileSync('backtest/results/phase4_3-full.json',JSON.stringify({run,baselineTrades:baseline.trades,hardTrades:hard.trades,baseZones:baseStructure.rows,hardZones:hardStructure.rows},null,2))
let storage='local-only';if(!process.env.BACKTEST_LOCAL_ONLY&&process.env.MARKET_SYNC_URL&&process.env.MARKET_SYNC_TOKEN){const url=process.env.MARKET_SYNC_URL.replace(/\/api\/market-data.*$/,'/api/backtests'),response=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${process.env.MARKET_SYNC_TOKEN}`,'Content-Type':'application/json',...(process.env.SITES_BYPASS_TOKEN?{'OAI-Sites-Authorization':`Bearer ${process.env.SITES_BYPASS_TOKEN}`}:{})},body:JSON.stringify({...run,sections:sections.map(section=>({...section,id:`${runId}-${section.id}`}))})});if(!response.ok)throw Error(`D1 ${response.status}: ${await response.text()}`);storage='D1 saved'}
console.log(JSON.stringify({storage,baseline:baseline.summary,hard:hard.summary,falling:falling.entries,verdict},null,2))
