import{DatabaseSync}from'node:sqlite';import{existsSync,mkdirSync,readdirSync,readFileSync,writeFileSync}from'node:fs';import{join}from'node:path';
const root='.wrangler/state/v3/d1/miniflare-D1DatabaseObject',file=existsSync(root)?readdirSync(root).find(x=>x.endsWith('.sqlite')&&x!=='metadata.sqlite'):null;if(!file)throw Error('로컬 TOSS D1 데이터가 없습니다');const db=new DatabaseSync(join(root,file),{readOnly:true}),raw=db.prepare("SELECT ticker,market_date date,high,low,close FROM daily_prices WHERE source='TOSS' ORDER BY ticker,market_date").all();db.close();
const history=Object.groupBy(raw,x=>x.ticker),source=JSON.parse(readFileSync('backtest/results/phase1_5-full.json','utf8')).records,records=new Map(source.map(x=>[`${x.ticker}|${x.date}`,x])),tickers=['AAPL','AMZN','AVGO','GOOG','META','MSFT','NVDA','TSLA'].filter(t=>history[t]?.length>504),avg=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null,med=x=>{const a=[...x].sort((a,b)=>a-b);return a.length?a[Math.floor(a.length/2)]:null},valid=x=>typeof x==='number'&&Number.isFinite(x),clamp=(x,min,max)=>Math.max(min,Math.min(max,x));
const ma=(p,n)=>p.length<n?null:avg(p.slice(-n).map(x=>x.close)),annualMdd=(p,y)=>{let peak=-Infinity,draw=0;for(const x of p)if(x.date.startsWith(String(y))){peak=Math.max(peak,x.close);draw=Math.min(draw,x.close/peak-1)}return peak===-Infinity?null:draw},atr=p=>{const q=p.slice(-15);return q.length<15?null:avg(q.slice(1).map((x,i)=>Math.max(x.high-x.low,Math.abs(x.high-q[i].close),Math.abs(x.low-q[i].close))))},score=r=>Math.round(((r.mdd??0)+(r.relative??0)+(r.stability??0))/65*100),curveMdd=curve=>{let peak=curve[0]??1,draw=0;for(const x of curve){peak=Math.max(peak,x);draw=Math.min(draw,x/peak-1)}return draw};
function zone(p,type,directional){const last=p.at(-1);if(!last||p.length<252)return null;const price=last.close,recent=p.slice(-60),trail=p.slice(-252),years=[...new Set(p.map(x=>Number(x.date.slice(0,4))))].slice(-5),ref=med(years.map(y=>annualMdd(p,y)).filter(valid).map(Math.abs)),high52=Math.max(...trail.map(x=>x.high)),low52=Math.min(...trail.map(x=>x.low)),mas=[['ma60',ma(p,60)],['ma120',ma(p,120)],['ma200',ma(p,200)]],tol=clamp((atr(p)??price*.03)/price*1.25,.015,.08),raw=type==='buy'?[['swing60',Math.min(...recent.map(x=>x.low))],['low52',low52],['mdd',ref===null?null:high52*(1-ref)],...mas]:[['swing60',Math.max(...recent.map(x=>x.high))],['high52',high52],['ath',Math.max(...p.map(x=>x.close))],...mas.map(([n,v])=>[n,valid(v)&&v>price?v:null])],items=raw.filter(([,v])=>valid(v)).filter(([n,v])=>!(type==='buy'&&directional&&n.startsWith('ma')&&v>price)).map(([n,v])=>({n,v}));if(!items.length)return null;let best=[];for(const c of items){const group=items.filter(x=>Math.abs(x.v-c.v)/price<=tol);if(group.length>best.length)best=group}if(best.length<2){const eligible=items.filter(x=>type==='buy'?x.v<=price*1.15:x.v>=price*.85),near=[...(eligible.length?eligible:items)].sort((a,b)=>Math.abs(a.v-price)-Math.abs(b.v-price))[0],band=Math.max(near.v*.005,price*tol*.25);return{low:near.v-band,mid:near.v,high:near.v+band,width:band*2/near.v}}const values=best.map(x=>x.v);return{low:Math.min(...values),mid:med(values),high:Math.max(...values),width:(Math.max(...values)-Math.min(...values))/med(values)}}
function structure(directional,active=tickers){const rows=[];for(const ticker of active){const p=history[ticker];for(let i=252;i<p.length-252;i++){const q=p.slice(0,i+1),buy=zone(q,'buy',directional),sell=zone(q,'sell',directional);rows.push({ticker,price:p[i].close,buy,sell})}}const metric=x=>{const buy=x.filter(r=>r.buy),sell=x.filter(r=>r.sell),both=x.filter(r=>r.buy&&r.sell);return{buyMeanWidth:avg(buy.map(r=>r.buy.width)),buyMedianWidth:med(buy.map(r=>r.buy.width)),sellMeanWidth:avg(sell.map(r=>r.sell.width)),sellMedianWidth:med(sell.map(r=>r.sell.width)),overlapRate:both.length?both.filter(r=>r.buy.high>=r.sell.low).length/both.length:null,buyAbovePriceRate:buy.length?buy.filter(r=>r.buy.high>r.price).length/buy.length:null,zoneCount:both.length}};return{rows,metric:metric(rows),byTicker:active.map(t=>({ticker:t,...metric(rows.filter(r=>r.ticker===t))}))}}
function simulate(directional,active=tickers){const trades=[],curves={};for(const ticker of active){const p=history[ticker],start=Math.max(252,p.findIndex(x=>records.has(`${ticker}|${x.date}`))),end=p.length-253;let cash=1,shares=0,pos=null,curve=[];for(let i=start;i<=end;i++){const day=p[i],record=records.get(`${ticker}|${day.date}`);if(!pos&&record&&score(record)>=70){const buy=zone(p.slice(0,i+1),'buy',directional),sell=zone(p.slice(0,i+1),'sell',directional);if(buy&&sell&&sell.mid>buy.mid&&day.low<=buy.mid&&day.high>=buy.mid){shares=cash*.9995/buy.mid;cash=0;pos={i,entry:buy.mid,target:sell.mid,low:day.low,high:day.high}}}else if(pos){pos.low=Math.min(pos.low,day.low);pos.high=Math.max(pos.high,day.high);if(i>pos.i&&day.low<=pos.target&&day.high>=pos.target){cash=shares*pos.target*.9995;trades.push({ticker,closed:true,days:i-pos.i,net:pos.target/pos.entry*.999**1-1,mae:Math.min(0,pos.low/pos.entry-1),mfe:pos.high/pos.entry-1});shares=0;pos=null}}curve.push(cash+shares*day.close)}if(pos){const last=p[end],value=cash+shares*last.close;trades.push({ticker,closed:false,days:end-pos.i,net:last.close/pos.entry*.9995-1,mae:Math.min(0,pos.low/pos.entry-1),mfe:pos.high/pos.entry-1});curve[curve.length-1]=value}curves[ticker]=curve}const summarize=(list,curve)=>{const done=list.filter(x=>x.closed);return{entries:list.length,closed:done.length,arrivalRate:list.length?done.length/list.length:null,medianReturn:med(done.map(x=>x.net)),cumulative:curve.at(-1)-1,mdd:curveMdd(curve),meanMae:avg(done.map(x=>x.mae)),meanMfe:avg(done.map(x=>x.mfe)),medianDays:med(done.map(x=>x.days)),openRate:list.length?(list.length-done.length)/list.length:null}},curve=Array.from({length:Math.max(...Object.values(curves).map(x=>x.length))},(_,i)=>avg(Object.values(curves).map(x=>x[Math.min(i,x.length-1)]))),overall=summarize(trades,curve),perTicker=active.map(t=>{const tTrades=trades.filter(x=>x.ticker===t),c=curves[t];return{ticker:t,...summarize(tTrades,c)}});return{overall,perTicker}}
function evaluate(directional,active=tickers){const s=structure(directional,active),p=simulate(directional,active);return{...s.metric,...p.overall,perTicker:s.byTicker.map(x=>({...x,...p.perTicker.find(y=>y.ticker===x.ticker)}))}}
const baseline=evaluate(false),directional=evaluate(true),leave=tickers.map(exclude=>({exclude,baseline:evaluate(false,tickers.filter(t=>t!==exclude)),directional:evaluate(true,tickers.filter(t=>t!==exclude))})),date=new Date().toISOString().slice(0,10),runId=`phase3-7-${date}`,rows=[{label:'Baseline',...baseline},{label:'MA 방향성',...directional}],sections=[
  ['structure','가격대 구조 비교',rows],
  ['fixed','Fixed 운용성과',rows],
  ['ticker','종목별 결과',baseline.perTicker.map(x=>({label:`Baseline ${x.ticker}`,...x})).concat(directional.perTicker.map(x=>({label:`MA 방향성 ${x.ticker}`,...x})))],
  ['leave','Leave-One-Stock-Out',leave.flatMap(x=>[
    {label:`Baseline · ${x.exclude} 제외`,medianReturn:x.baseline.medianReturn,mdd:x.baseline.mdd,overlapRate:x.baseline.overlapRate},
    {label:`MA 방향성 · ${x.exclude} 제외`,medianReturn:x.directional.medianReturn,mdd:x.directional.mdd,overlapRate:x.directional.overlapRate}
  ])],
  ['conclusion','최종 판단',[{label:'중첩률',baseline:baseline.overlapRate,directional:directional.overlapRate},{label:'현재가 위 매수구간',baseline:baseline.buyAbovePriceRate,directional:directional.buyAbovePriceRate}]]
].map(([id,title,data],i)=>({id,parentId:null,sectionType:'report',title,summary:'실제 TOSS 일봉 독립 재시뮬레이션',reportData:{rows:data},sortOrder:i+1}));
const result={baseline,directional,leave},run={id:runId,runDate:date,phase:'3.7차 · MA 방향성 최종 검증',title:'MA 방향성 구조·운용성과·종목 의존 검증',algorithmVersion:'BT-v3.7',periodStart:'2022-01-25',periodEnd:'2025-08-21',universe:'TOSS 8종목 동일 스냅샷',config:{atrCap:.08,atrMultiplier:1.25,minTolerance:.015,scoreThreshold:70,weights:'30/20/15',entry:'buy midpoint touch',exit:'entry-day fixed sell midpoint',warmup:252,lookAheadGuard:true},summary:result,conclusion:'MA 방향성만 변경한 독립 재시뮬레이션입니다. 운영 앱 값은 자동 변경하지 않습니다.',createdAt:new Date().toISOString(),sections};
mkdirSync('backtest/results',{recursive:true});writeFileSync('backtest/results/phase3_7-summary.json',JSON.stringify(run,null,2));writeFileSync('backtest/results/phase3_7-full.json',JSON.stringify(result,null,2));for(const[name,data]of Object.entries({structure:rows,per_ticker:sections[2].reportData.rows,leave_one_out:sections[3].reportData.rows}))writeFileSync(`backtest/results/phase3_7-${name}.json`,JSON.stringify(data,null,2));const stored={...run,sections:sections.map(s=>({...s,id:`${runId}-${s.id}`}))};let storage='local-only';if(!process.env.BACKTEST_LOCAL_ONLY&&process.env.MARKET_SYNC_URL&&process.env.MARKET_SYNC_TOKEN){const u=process.env.MARKET_SYNC_URL.replace(/\/api\/market-data.*$/,'/api/backtests'),r=await fetch(u,{method:'POST',headers:{Authorization:`Bearer ${process.env.MARKET_SYNC_TOKEN}`,'Content-Type':'application/json',...(process.env.SITES_BYPASS_TOKEN?{'OAI-Sites-Authorization':`Bearer ${process.env.SITES_BYPASS_TOKEN}`}:{})},body:JSON.stringify(stored)});if(!r.ok)throw Error(`D1 ${r.status}: ${await r.text()}`);storage='D1 saved'}console.log(JSON.stringify({storage,...result},null,2));
