import { DatabaseSync } from 'node:sqlite'
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const top10=['NVDA','AAPL','GOOG','MSFT','AMZN','AVGO','SPCX','META','TSLA','BRK-B'],warmup=252,horizons=[20,60,120,252]
const root='.wrangler/state/v3/d1/miniflare-D1DatabaseObject',file=existsSync(root)?readdirSync(root).find(name=>name.endsWith('.sqlite')&&name!=='metadata.sqlite'):null
if(!file)throw new Error('로컬 TOSS D1 데이터가 없습니다.')
const db=new DatabaseSync(join(root,file),{readOnly:true}),raw=db.prepare(`SELECT ticker,market_date date,open,high,low,close,volume FROM daily_prices WHERE source='TOSS' AND ticker IN (${top10.map(()=>'?').join(',')}) ORDER BY ticker,market_date`).all(...top10)
db.close(); const rows=Object.groupBy(raw,row=>row.ticker),usable=Object.fromEntries(Object.entries(rows).filter(([,v])=>v.length>warmup))
const avg=(xs)=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null,med=(xs)=>{const a=[...xs].sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:null},clamp=(n)=>Math.max(0,Math.min(1,n))
const ma=(points,n)=>points.length<n?null:avg(points.slice(-n).map(x=>x.close))
const annualMdd=(points,year)=>{let peak=-Infinity,m=0;for(const p of points.filter(x=>x.date.startsWith(String(year)))){peak=Math.max(peak,p.high);m=Math.min(m,p.close/peak-1)}return peak===-Infinity?null:m}
const metrics=(points,index,peers)=>{const past=points.slice(0,index+1),p=past.at(-1),trailing=past.slice(-252),high=Math.max(...trailing.map(x=>x.high)),low=Math.min(...trailing.map(x=>x.low)),dd=p.close/high-1,years=[...new Set(past.map(x=>Number(x.date.slice(0,4))))].filter(y=>y<=Number(p.date.slice(0,4))),mdds=years.map(y=>annualMdd(past,y)).filter(x=>x!==null).map(Math.abs),ref=med(mdds),mddScore=ref===null?null:30*clamp(Math.abs(dd)/ref),ma20=ma(past,20),ma60=ma(past,60),recentLow=Math.min(...past.slice(-20).map(x=>x.low)),stability=recentLow>=Math.min(...past.slice(-40,-20).map(x=>x.low))&&ma20!==null&&ma60!==null?(p.close>=ma20&&p.close>=ma60?15:p.close>=ma20?11:5):0
  const peerDds=peers.map(peer=>{const q=peer.filter(x=>x.date<=p.date);if(q.length<252)return null;const t=q.slice(-252);return{ticker:q[0].ticker,dd:q.at(-1).close/Math.max(...t.map(x=>x.high))-1}}).filter(Boolean).sort((a,b)=>a.dd-b.dd),rank=peerDds.findIndex(x=>x.ticker===p.ticker),relative=rank<0?null:peerDds.length===1?20:20*(peerDds.length-1-rank)/(peerDds.length-1),available=[mddScore,relative,stability].filter(x=>x!==null),score=available.length?Math.round(available.reduce((a,b)=>a+b,0)/(available.length===3?65:available.length===2?50:15)*100):null
  const refs=[Math.min(...past.slice(-60).map(x=>x.low)),low,ma60,ma(past,120),ma(past,200)].filter(x=>x!==null),zone=refs.length?med(refs):null,tolerance=Math.max(.02,Math.abs(dd)*.1)
  return{score,dd,stability,zoneLow:zone===null?null:zone*(1-tolerance),zoneHigh:zone===null?null:zone*(1+tolerance),date:p.date,price:p.close}
}
const outcomes=(points,index)=>Object.fromEntries(horizons.map(h=>{const future=points.slice(index+1,index+1+h),base=points[index].close;if(future.length<h)return[h,null];const closes=future.map(x=>x.close);return[h,{return:future.at(-1).close/base-1,maxUp:Math.max(...closes)/base-1,maxDown:Math.min(...future.map(x=>x.low))/base-1}]}))
const events=[],all=Object.values(usable)
for(const [ticker,points] of Object.entries(usable))for(let i=warmup;i<points.length-252;i++){const m=metrics(points,i,all),o=outcomes(points,i),hit=m.zoneLow!==null&&points[i].low<=m.zoneHigh&&points[i].high>=m.zoneLow;const prev=events.at(-1);if(hit&&prev?.ticker===ticker&&prev.zoneHit)continue;events.push({ticker,...m,zoneHit:hit,outcomes:o})}
const summarize=(items)=>Object.fromEntries(horizons.map(h=>{const data=items.map(x=>x.outcomes[h]).filter(Boolean);return[h,{n:data.length,mean:avg(data.map(x=>x.return)),median:med(data.map(x=>x.return)),positive:avg(data.map(x=>x.return>0?1:0)),maxUp:avg(data.map(x=>x.maxUp)),maxDown:avg(data.map(x=>x.maxDown))}]}))
const buckets=['0-49','50-59','60-69','70-79','80-89','90-100'].map(label=>{const [a,b]=label.split('-').map(Number),items=events.filter(x=>x.score!==null&&x.score>=a&&x.score<=b);return{label,count:items.length,results:summarize(items)}})
const conditions=[['일반 평가 가능 거래일',events],... [60,70,80,90].map(n=>[`점수 ${n} 이상`,events.filter(x=>x.score>=n)]),['핵심가격 도달',events.filter(x=>x.zoneHit)],...[60,70,80,90].map(n=>[`복합 · 도달 + ${n} 이상`,events.filter(x=>x.zoneHit&&x.score>=n)])].map(([label,items])=>({label,count:items.length,results:summarize(items)}))
const zoneEvents=events.filter(x=>x.zoneHit),failure=events.filter(x=>x.score>=90&&x.outcomes[60]?.return<-.15).sort((a,b)=>a.outcomes[60].return-b.outcomes[60].return).slice(0,5).map(x=>({ticker:x.ticker,date:x.date,score:x.score,return60:x.outcomes[60].return,reason:'가격기반 고점수였으나 이후 60거래일 종가가 하락'}))
const byTicker=Object.entries(usable).map(([ticker])=>{const x=events.filter(e=>e.ticker===ticker&&e.zoneHit);const r=x.map(e=>e.outcomes[60]).filter(Boolean);return{ticker,events:x.length,median60:med(r.map(v=>v.return)),median120:med(x.map(e=>e.outcomes[120]).filter(Boolean).map(v=>v.return)),successRate:avg(r.map(v=>v.return>0?1:0)),averageMaxDown:avg(r.map(v=>v.maxDown))}})
const baseline=conditions[0].results[60]?.median,combo=conditions.find(x=>x.label==='복합 · 도달 + 70 이상')?.results[60]?.median
const conclusion=combo!==null&&baseline!==null&&combo>baseline?'복합조건은 이번 표본에서 일반 평가일보다 60일 중앙값이 높았습니다. 표본 수가 적은 구간은 추가 검증이 필요합니다.':'복합조건의 우위가 이번 표본에서 뚜렷하지 않았습니다. 임계값과 시장환경을 나눠 추가 검증이 필요합니다.'
const runDate=new Date().toISOString().slice(0,10),periodStart=Object.values(usable).map(x=>x[warmup]?.date).sort().at(0),periodEnd=Object.values(usable).map(x=>x.at(-253)?.date).sort().at(-1)
const summary={eventCount:events.length,zoneEvents:zoneEvents.length,tickers:Object.keys(usable),excluded:top10.filter(x=>!usable[x]),periodStart,periodEnd,buckets,conditions,byTicker,failures:failure,limitations:['현재 시총 TOP10을 과거에 고정 적용한 회고형 테스트로 survivorship bias가 있습니다.','과거 EPS/PER는 포함하지 않은 가격기반 기회점수입니다.','약 1,000개 이상 TOSS 일봉과 252거래일 워밍업만 사용했습니다.']}
const run={id:`phase1-${runDate}`,runDate,phase:'1차 · 앱 판단로직 검증',title:'가격기반 기회점수·핵심가격대 검증',algorithmVersion:'BT-v1.0',periodStart,periodEnd,universe:'시총 TOP10 (현재 구성)',config:{warmup,weights:[30,20,15],horizons,lookAheadGuard:true},summary,conclusion,createdAt:new Date().toISOString(),sections:[{id:'opportunity',sectionType:'experiment',title:'기회점수 검증',summary:'가격기반 기회점수 구간별 이후 성과',reportData:{buckets},sortOrder:1},{id:'zones',sectionType:'experiment',title:'핵심가격대 검증',summary:'매수 핵심가격 도달 이벤트의 이후 반응',reportData:{count:zoneEvents.length,results:summarize(zoneEvents)},sortOrder:2},{id:'combined',sectionType:'experiment',title:'복합효과 검증',summary:'기회점수와 핵심가격대 조건 비교',reportData:{conditions},sortOrder:3},{id:'failures',sectionType:'case',title:'대표 실패 사례',summary:'고점수·후속 하락 사례',reportData:{failures:failure,byTicker},sortOrder:4}]}
mkdirSync('backtest/results',{recursive:true});writeFileSync('backtest/results/phase1-full.json',JSON.stringify({run,events},null,2));writeFileSync('backtest/results/phase1-summary.json',JSON.stringify(run,null,2));writeFileSync('backtest/results/phase1-events.csv',['ticker,date,score,zone_hit,return20,return60,return120,return252',...events.map(x=>[x.ticker,x.date,x.score,x.zoneHit,...horizons.map(h=>x.outcomes[h]?.return??'')].join(','))].join('\n'))
if(process.env.MARKET_SYNC_URL&&process.env.MARKET_SYNC_TOKEN){const url=process.env.MARKET_SYNC_URL.replace(/\/api\/market-data.*$/,'/api/backtests'),res=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${process.env.MARKET_SYNC_TOKEN}`,'Content-Type':'application/json',...(process.env.SITES_BYPASS_TOKEN?{'OAI-Sites-Authorization':`Bearer ${process.env.SITES_BYPASS_TOKEN}`}:{})},body:JSON.stringify(run)});if(!res.ok)throw new Error(`D1 저장 실패 ${res.status}: ${await res.text()}`)}
console.log(JSON.stringify({runDate,periodStart,periodEnd,events:events.length,zoneEvents:zoneEvents.length,excluded:summary.excluded,conclusion},null,2))
