import { marketDataSchemas, marketSnapshotsSchema } from '../db/schema'
import { defaultCatalog, emptyMarketOverview } from '../src/data/defaultCatalog'
import { calculateMddProximity, calculateMetrics, calculatePriceStability } from '../src/services/metricsCalculator'
import { isStoredPriceStale } from '../src/services/marketHours'
import type { FundamentalHistoryPoint, HistoricalPrice, MarketCatalog, MarketOverviewItem, StockDataSources, StockFundamentals, StockQuote } from '../src/types'
import { loadGoogleFinanceSheet, loadGoogleFinanceWorkbook, type GoogleFinanceRecord, type GoogleFinanceWorkbook } from './google-finance-sheets'
import { loadTossDailyPrices, loadTossPrices, type TossCredentials } from './toss-securities'

type SnapshotRow = { payload:string; market_date:string|null; updated_at:string; refresh_cycle:string }
type StoredPayload = { quote:StockQuote|null; fundamentals:StockFundamentals|null; historicalPrices:HistoricalPrice[]; historyComplete:boolean; updatedAt:string; refreshCycle:string; fundamentalsUpdatedAt?:string|null; sources?:StockDataSources; providerMetrics?:{high52:number|null;low52:number|null}; storageSource?:'d1'|'supabase'; stale?:boolean; fundamentalsHistory?:FundamentalHistoryPoint[] }
export type RefreshSource = { configured:boolean; attempted:boolean; status:'ok'|'partial'|'failed'|'skipped'; updated:number; error?:string }
export type RefreshReport = { status:'success'|'partial'|'failed'; trigger:'manual'|'scheduled'; startedAt:string; completedAt:string; marketDate:string|null; sources:{toss:RefreshSource;google:RefreshSource;supabase:RefreshSource}; marketOverview:Record<MarketOverviewItem['key'],'ok'|'failed'> }
type DashboardMeta = { catalog:MarketCatalog; marketOverview:MarketOverviewItem[]; updatedAt:string|null; refreshCycle:string|null; lastRefresh?:RefreshReport|null }
export type MarketBindings = { TOSS_CLIENT_ID?:string; TOSS_CLIENT_SECRET?:string; GOOGLE_SHEETS_ID?:string; GOOGLE_SHEETS_API_KEY?:string; GOOGLE_SHEETS_MASTER_RANGE?:string; GOOGLE_SHEETS_MARKET_RANGE?:string; SUPABASE_URL?:string; SUPABASE_SERVICE_ROLE_KEY?:string }
type SyncBindings = MarketBindings & { MARKET_SYNC_TOKEN?:string }
type TossSyncItem = { quote:StockQuote; historicalPrices:HistoricalPrice[] }

const validSymbol=(value:string)=>/^[A-Z][A-Z0-9.-]{0,9}$/.test(value)
const refreshCycle=(now=new Date())=>{const kst=new Date(now.getTime()+9*60*60*1000);if(kst.getUTCHours()<6||(kst.getUTCHours()===6&&kst.getUTCMinutes()<40))kst.setUTCDate(kst.getUTCDate()-1);return kst.toISOString().slice(0,10)}
const response=(body:unknown,cache:string,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'private, no-store','X-Market-Cache':cache}})
const tossCredentials=(bindings:MarketBindings):TossCredentials|null=>bindings.TOSS_CLIENT_ID&&bindings.TOSS_CLIENT_SECRET?{clientId:bindings.TOSS_CLIENT_ID,clientSecret:bindings.TOSS_CLIENT_SECRET}:null
const supabaseConfigured=(bindings:MarketBindings)=>Boolean(bindings.SUPABASE_URL&&bindings.SUPABASE_SERVICE_ROLE_KEY)
const googleConfigured=(bindings:MarketBindings)=>Boolean(bindings.GOOGLE_SHEETS_ID&&bindings.GOOGLE_SHEETS_API_KEY)
const storedSource=(value:StockDataSources[keyof StockDataSources]|undefined,fallback:StockDataSources[keyof StockDataSources]):StockDataSources[keyof StockDataSources]=>value&&String(value)!=='stored'?value:fallback
const storedView=(payload:StoredPayload)=>{const marketDate=payload.quote?.marketDate??payload.historicalPrices.at(-1)?.date??null;return{...payload,storageSource:'d1' as const,stale:isStoredPriceStale(marketDate),sources:{price:'toss' as const,history:'toss' as const,high52:'app_calculated' as const,low52:'app_calculated' as const,mdd:'app_calculated' as const,ma:'app_calculated' as const,priceStability:'app_calculated' as const,marketCap:storedSource(payload.sources?.marketCap,'googlefinance'),pe:storedSource(payload.sources?.pe,'googlefinance'),eps:storedSource(payload.sources?.eps,'googlefinance'),sector:storedSource(payload.sources?.sector,'reference'),company:storedSource(payload.sources?.company,'reference')}}}

const finite=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)
export function verifiedTossSyncItem(symbol:string,value:unknown):TossSyncItem|null{
  if(!value||typeof value!=='object')return null
  const candidate=value as Partial<TossSyncItem>,quote=candidate.quote
  if(!quote||quote.ticker!==symbol||!finite(quote.price)||!/^\d{4}-\d{2}-\d{2}$/.test(quote.marketDate??''))return null
  const prices=(Array.isArray(candidate.historicalPrices)?candidate.historicalPrices:[]).filter(point=>point&&/^\d{4}-\d{2}-\d{2}$/.test(point.date)&&[point.open,point.high,point.low,point.close,point.volume].every(finite)&&point.low!>0&&point.low!<=point.high!&&point.open!>=point.low!&&point.open!<=point.high!&&point.close>=point.low!&&point.close<=point.high!).sort((a,b)=>a.date.localeCompare(b.date)).slice(-1000)
  if(!prices.length||prices.at(-1)!.date!==quote.marketDate)return null
  return{quote:{...quote,previousClose:prices.at(-2)?.close??null,changePercent:prices.at(-2)?.close?quote.price!/prices.at(-2)!.close-1:null},historicalPrices:prices}
}

const authorizedSync=async(request:Request,token:string|undefined)=>{const supplied=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'')??'',bytes=new TextEncoder();if(!token||!supplied)return false;const [a,b]=await Promise.all([crypto.subtle.digest('SHA-256',bytes.encode(token)),crypto.subtle.digest('SHA-256',bytes.encode(supplied))]);return Array.from(new Uint8Array(a)).every((value,index)=>value===new Uint8Array(b)[index])}

async function importTossSync(request:Request,db:D1Database,bindings:SyncBindings){
  if(!(await authorizedSync(request,bindings.MARKET_SYNC_TOKEN)))return response({error:'Unauthorized'},'SYNC-DENIED',401)
  let body:{payloads?:Record<string,unknown>};try{body=await request.json() as {payloads?:Record<string,unknown>}}catch{return response({error:'Invalid JSON'},'SYNC-INVALID',400)}
  const entries=Object.entries(body.payloads??{});if(!entries.length||entries.length>100)return response({error:'Invalid payload count'},'SYNC-INVALID',400)
  let imported=0,rejected=0,latest:string|null=null
  for(const [rawSymbol,value] of entries){const symbol=rawSymbol.trim().toUpperCase(),fresh=validSymbol(symbol)?verifiedTossSyncItem(symbol,value):null;if(!fresh){rejected+=1;continue}const existing=await loadStored(db,symbol);if(existing.row?.market_date&&existing.row.market_date>fresh.quote.marketDate!){rejected+=1;continue}const payload=refreshedPayload(symbol,existing.payload,undefined,fresh.quote,fresh.historicalPrices);if(!payload){rejected+=1;continue}payload.historicalPrices=fresh.historicalPrices;payload.quote=fresh.quote;payload.sources={...payload.sources!,price:'toss',history:'toss'};payload.storageSource='d1';payload.stale=isStoredPriceStale(fresh.quote.marketDate);await saveStored(db,symbol,payload,fresh.quote.marketDate);await accumulate(db,bindings,symbol,payload);imported+=1;if(!latest||fresh.quote.marketDate!>latest)latest=fresh.quote.marketDate!}
  return response({status:rejected?'partial':'success',imported,rejected,marketDate:latest},'TOSS-SYNC',imported?200:422)
}

const snapshotSourceColumns={price_source:"TEXT NOT NULL DEFAULT 'TOSS'",eps_source:"TEXT NOT NULL DEFAULT 'GOOGLE_FINANCE'",per_source:"TEXT NOT NULL DEFAULT 'GOOGLE_FINANCE'",market_cap_source:"TEXT NOT NULL DEFAULT 'GOOGLE_FINANCE'",mdd_source:"TEXT NOT NULL DEFAULT 'APP_CALCULATED'",ma_source:"TEXT NOT NULL DEFAULT 'APP_CALCULATED'",price_stability_source:"TEXT NOT NULL DEFAULT 'APP_CALCULATED'"} as const
async function ensureSchema(db:D1Database){for(const schema of [marketSnapshotsSchema,...marketDataSchemas])await db.prepare(schema).run();const columns=await db.prepare('PRAGMA table_info(stock_snapshots)').all<{name:string}>(),existing=new Set(columns.results.map(column=>column.name));for(const [name,type] of Object.entries(snapshotSourceColumns))if(!existing.has(name))await db.prepare(`ALTER TABLE stock_snapshots ADD COLUMN ${name} ${type}`).run();await db.prepare("UPDATE daily_prices SET source='TOSS' WHERE source='toss'").run()}
async function loadStored(db:D1Database,symbol:string){const row=await db.prepare('SELECT payload, market_date, updated_at, refresh_cycle FROM market_snapshots WHERE symbol = ?1').bind(symbol).first<SnapshotRow>();if(!row)return{row:null,payload:null};try{return{row,payload:JSON.parse(row.payload) as StoredPayload}}catch{return{row,payload:null}}}
async function saveStored(db:D1Database,symbol:string,payload:StoredPayload,marketDate:string|null){await db.prepare('INSERT INTO market_snapshots (symbol,payload,market_date,updated_at,refresh_cycle) VALUES (?1,?2,?3,?4,?5) ON CONFLICT(symbol) DO UPDATE SET payload=excluded.payload,market_date=excluded.market_date,updated_at=excluded.updated_at,refresh_cycle=excluded.refresh_cycle').bind(symbol,JSON.stringify(payload),marketDate,payload.updatedAt,payload.refreshCycle).run()}
async function loadDashboardMeta(db:D1Database):Promise<DashboardMeta>{const entry=await loadStored(db,'__DASHBOARD__');if(!entry.row?.payload)return{catalog:defaultCatalog,marketOverview:emptyMarketOverview,updatedAt:null,refreshCycle:null,lastRefresh:null};try{return JSON.parse(entry.row.payload) as DashboardMeta}catch{return{catalog:defaultCatalog,marketOverview:emptyMarketOverview,updatedAt:null,refreshCycle:null,lastRefresh:null}}}
async function saveDashboardMeta(db:D1Database,meta:DashboardMeta){await db.prepare("INSERT INTO market_snapshots (symbol,payload,market_date,updated_at,refresh_cycle) VALUES ('__DASHBOARD__',?1,NULL,?2,?3) ON CONFLICT(symbol) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at,refresh_cycle=excluded.refresh_cycle").bind(JSON.stringify(meta),meta.updatedAt??new Date().toISOString(),meta.refreshCycle??refreshCycle()).run()}
async function saveDailyPrices(db:D1Database,ticker:string,prices:HistoricalPrice[]){const sql='INSERT OR IGNORE INTO daily_prices (ticker,market_date,open,high,low,close,volume,source) VALUES (?1,?2,?3,?4,?5,?6,?7,?8)';for(let index=0;index<prices.length;index+=100)await db.batch(prices.slice(index,index+100).map(point=>db.prepare(sql).bind(ticker,point.date,point.open??null,point.high??null,point.low??null,point.close,point.volume??null,'TOSS')))}
async function saveSnapshot(db:D1Database,payload:Record<string,unknown>){await db.prepare('INSERT OR IGNORE INTO stock_snapshots (ticker,snapshot_date,price,eps,per,market_cap,drawdown_52w,mdd_reference,mdd_proximity,ma20,ma60,ma120,ma200,price_stability,price_source,eps_source,per_source,market_cap_source,mdd_source,ma_source,price_stability_source) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19,?20,?21)').bind(payload.ticker,payload.snapshot_date,payload.price,payload.eps,payload.per,payload.market_cap,payload.drawdown_52w,payload.mdd_reference,payload.mdd_proximity,payload.ma20,payload.ma60,payload.ma120,payload.ma200,payload.price_stability,payload.price_source,payload.eps_source,payload.per_source,payload.market_cap_source,payload.mdd_source,payload.ma_source,payload.price_stability_source).run()}
async function loadFundamentalsHistory(db:D1Database,ticker:string):Promise<FundamentalHistoryPoint[]>{const result=await db.prepare('SELECT snapshot_date, eps, per FROM stock_snapshots WHERE ticker = ?1 AND snapshot_date >= ?2 ORDER BY snapshot_date ASC').bind(ticker,'2026-08-20').all<{snapshot_date:string;eps:number|null;per:number|null}>();return result.results.map(row=>({snapshotDate:row.snapshot_date,eps:row.eps,per:row.per}))}
async function withFundamentalsHistory(db:D1Database,payloads:Record<string,StoredPayload>){await Promise.all(Object.entries(payloads).map(async([ticker,payload])=>{payload.fundamentalsHistory=await loadFundamentalsHistory(db,ticker)}));return payloads}
async function saveSupabase(bindings:MarketBindings,table:string,rows:Record<string,unknown>[],conflict:string){if(!rows.length||!bindings.SUPABASE_URL||!bindings.SUPABASE_SERVICE_ROLE_KEY)return false;const url=`${bindings.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/${table}?on_conflict=${encodeURIComponent(conflict)}`;const result=await fetch(url,{method:'POST',headers:{apikey:bindings.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${bindings.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(rows)});if(!result.ok)throw new Error(`Supabase ${table} ${result.status}`);return true}

const mergePrices=(stored:HistoricalPrice[],fresh:HistoricalPrice[])=>[...new Map([...stored,...fresh].map(point=>[point.date,point])).values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-1000)
const mergeOverview=(stored:MarketOverviewItem[],fresh:MarketOverviewItem[])=>emptyMarketOverview.map(base=>{const previous=stored.find(item=>item.key===base.key),next=fresh.find(item=>item.key===base.key);return next?.value!==null&&next?.value!==undefined?next:previous?.value!==null&&previous?.value!==undefined?previous:{...base}})
const overviewStatus=(items:MarketOverviewItem[])=>Object.fromEntries(emptyMarketOverview.map(base=>[base.key,items.find(item=>item.key===base.key)?.value!==null&&items.find(item=>item.key===base.key)?.value!==undefined?'ok':'failed'])) as RefreshReport['marketOverview']

function refreshedPayload(symbol:string,stored:StoredPayload|null,gf:GoogleFinanceRecord|undefined,quote:StockQuote|undefined,freshPrices:HistoricalPrice[]):StoredPayload|null{
  const historicalPrices=mergePrices(stored?.historicalPrices??[],freshPrices),latest=historicalPrices.at(-1),previous=historicalPrices.at(-2)
  const nextQuote=quote?{...quote,previousClose:previous?.close??null,changePercent:quote.price&&previous?.close?quote.price/previous.close-1:null,marketDate:quote.marketDate??latest?.date??null}:stored?.quote??(latest?{ticker:symbol,price:latest.close,previousClose:previous?.close??null,changePercent:previous?.close?latest.close/previous.close-1:null,marketDate:latest.date}:null)
  const current=gf?.fundamentals,old=stored?.fundamentals
  const fundamentals:StockFundamentals={ticker:symbol,companyName:current?.companyName??old?.companyName??null,sector:current?.sector??old?.sector??null,marketCap:current?.marketCap??old?.marketCap??null,pe:current?.pe??old?.pe??null,eps:current?.eps??old?.eps??null}
  if(!nextQuote&&!historicalPrices.length&&!current)return stored
  const historySource:StockDataSources['history']='toss',priceSource:StockDataSources['price']='toss'
  const source=(value:unknown,fallback:StockDataSources[keyof StockDataSources])=>value!==null&&value!==undefined?'googlefinance' as const:fallback
  const updatedAt=new Date().toISOString()
  return{quote:nextQuote,fundamentals,historicalPrices,historyComplete:false,updatedAt,refreshCycle:refreshCycle(),fundamentalsUpdatedAt:current?updatedAt:stored?.fundamentalsUpdatedAt??null,storageSource:'d1',stale:false,sources:{price:priceSource,history:historySource,high52:'app_calculated',low52:'app_calculated',mdd:'app_calculated',ma:'app_calculated',priceStability:'app_calculated',marketCap:source(current?.marketCap,storedSource(stored?.sources?.marketCap,'googlefinance')),pe:source(current?.pe,storedSource(stored?.sources?.pe,'googlefinance')),eps:source(current?.eps,storedSource(stored?.sources?.eps,'googlefinance')),sector:storedSource(stored?.sources?.sector,'reference'),company:storedSource(stored?.sources?.company,'reference')},providerMetrics:{high52:null,low52:null}}
}

function snapshotOf(ticker:string,payload:StoredPayload){const marketDate=payload.quote?.marketDate??payload.historicalPrices.at(-1)?.date;if(!marketDate)return null;const currentYear=Number(marketDate.slice(0,4)),metrics=calculateMetrics(payload.historicalPrices,payload.quote?.price??null,currentYear,false),mddValues=[currentYear-2,currentYear-1,currentYear].map(year=>metrics.mdd[year]),proximity=calculateMddProximity(metrics.drawdown52,mddValues);return{ticker,snapshot_date:marketDate,price:payload.quote?.price??payload.historicalPrices.at(-1)?.close??null,eps:payload.fundamentals?.eps??null,per:payload.fundamentals?.pe??null,market_cap:payload.fundamentals?.marketCap??null,drawdown_52w:metrics.drawdown52,mdd_reference:mddValues.every(value=>typeof value==='number')?[...(mddValues as number[])].sort((a,b)=>Math.abs(a)-Math.abs(b))[1]:null,mdd_proximity:proximity?.ratio??null,ma20:metrics.ma20,ma60:metrics.ma60,ma120:metrics.ma120,ma200:metrics.ma200,price_stability:calculatePriceStability(payload.historicalPrices,metrics.ma20,metrics.ma60),price_source:'TOSS',eps_source:'GOOGLE_FINANCE',per_source:'GOOGLE_FINANCE',market_cap_source:'GOOGLE_FINANCE',mdd_source:'APP_CALCULATED',ma_source:'APP_CALCULATED',price_stability_source:'APP_CALCULATED'}}
async function accumulate(db:D1Database,bindings:MarketBindings,ticker:string,payload:StoredPayload){const snapshot=snapshotOf(ticker,payload);if(!snapshot)return{d1:false,supabase:false};await saveDailyPrices(db,ticker,payload.historicalPrices);await saveSnapshot(db,snapshot);let supabase=false;if(supabaseConfigured(bindings)){await Promise.all([saveSupabase(bindings,'daily_prices',payload.historicalPrices.map(point=>({ticker,market_date:point.date,open:point.open??null,high:point.high??null,low:point.low??null,close:point.close,volume:point.volume??null,source:'TOSS'})),'ticker,market_date'),saveSupabase(bindings,'stock_snapshots',[snapshot],'ticker,snapshot_date')]);supabase=true}return{d1:true,supabase}}

async function googleWorkbook(bindings:MarketBindings):Promise<GoogleFinanceWorkbook|null>{if(!bindings.GOOGLE_SHEETS_ID||!bindings.GOOGLE_SHEETS_API_KEY)return null;return loadGoogleFinanceWorkbook({spreadsheetId:bindings.GOOGLE_SHEETS_ID,apiKey:bindings.GOOGLE_SHEETS_API_KEY,masterRange:bindings.GOOGLE_SHEETS_MASTER_RANGE??'STOCK_MASTER!A1:Z1000',historyRange:'',marketRange:bindings.GOOGLE_SHEETS_MARKET_RANGE??'MARKET_OVERVIEW!A1:J30'})}

export async function refreshDashboard(db:D1Database,bindings:MarketBindings,trigger:'manual'|'scheduled',includeToss=trigger==='manual'){
  await ensureSchema(db);const startedAt=new Date().toISOString();let meta=await loadDashboardMeta(db),workbook:GoogleFinanceWorkbook|null=null,googleError:string|undefined
  if(googleConfigured(bindings))try{workbook=await googleWorkbook(bindings)}catch(error){googleError=error instanceof Error?error.message:'Google Sheets failed'}
  const catalog=workbook?.catalog.stocks.length&&workbook.catalog.groups.length?workbook.catalog:meta.catalog
  const mergedOverview=mergeOverview(meta.marketOverview,workbook?.marketOverview??[]),symbols=catalog.stocks.filter(stock=>stock.active).map(stock=>stock.ticker),stored=Object.fromEntries(await Promise.all(symbols.map(async symbol=>[symbol,await loadStored(db,symbol)] as const)))
  const credentials=includeToss?tossCredentials(bindings):null,listed=symbols.filter(symbol=>symbol!=='SPCX');let quotes:Record<string,StockQuote>={},tossError:string|undefined,tossUpdated=0,tossFailures=0
  if(credentials)try{quotes=await loadTossPrices(listed,credentials)}catch(error){tossError=error instanceof Error?error.message:'Toss failed'}
  const payloads:Record<string,StoredPayload>={},records=workbook?.records??{};let supabaseUpdated=0,supabaseFailures=0
  for(let index=0;index<symbols.length;index+=3){await Promise.all(symbols.slice(index,index+3).map(async symbol=>{const entry=stored[symbol];let freshPrices:HistoricalPrice[]=[];if(credentials&&!tossError&&symbol!=='SPCX')try{freshPrices=await loadTossDailyPrices(symbol,credentials,entry?.payload?.historicalPrices.length?1:5);tossUpdated+=freshPrices.length?1:0}catch{tossFailures+=1}const payload=refreshedPayload(symbol,entry?.payload??null,records[symbol],quotes[symbol],freshPrices);if(!payload)return;if(freshPrices.length||quotes[symbol])tossUpdated+=quotes[symbol]?1:0;const marketDate=payload.quote?.marketDate??payload.historicalPrices.at(-1)?.date??entry?.row?.market_date??null;await saveStored(db,symbol,payload,marketDate);try{const saved=await accumulate(db,bindings,symbol,payload);if(saved.supabase)supabaseUpdated+=1}catch{supabaseFailures+=1}payloads[symbol]=payload}))}
  const marketDate=Object.values(payloads).map(payload=>payload.quote?.marketDate??payload.historicalPrices.at(-1)?.date??null).filter((value):value is string=>Boolean(value)).sort().at(-1)??null
  const googleUpdated=(workbook?.marketOverview.filter(item=>item.value!==null).length??0)+Object.values(records).filter(record=>record.fundamentals&&[record.fundamentals.eps,record.fundamentals.pe,record.fundamentals.marketCap].some(value=>value!==null&&value!==undefined)).length
  const tossStatus:RefreshSource=!includeToss||!tossCredentials(bindings)?{configured:Boolean(tossCredentials(bindings)),attempted:false,status:'skipped',updated:0}:{configured:true,attempted:true,status:tossError||tossFailures?(tossUpdated?'partial':'failed'):'ok',updated:tossUpdated,...(tossError?{error:tossError}:{})}
  const googleStatus:RefreshSource=!googleConfigured(bindings)?{configured:false,attempted:false,status:'skipped',updated:0}:{configured:true,attempted:true,status:googleError||googleUpdated===0?(googleUpdated?'partial':'failed'):'ok',updated:googleUpdated,...(googleError?{error:googleError}:{})}
  const supabaseStatus:RefreshSource=!supabaseConfigured(bindings)?{configured:false,attempted:false,status:'skipped',updated:0}:{configured:true,attempted:true,status:supabaseFailures?(supabaseUpdated?'partial':'failed'):'ok',updated:supabaseUpdated}
  const attempted=[tossStatus,googleStatus,supabaseStatus].filter(source=>source.attempted),failed=attempted.filter(source=>source.status==='failed'||source.status==='partial'),status:RefreshReport['status']=!Object.keys(payloads).length&&!googleUpdated?'failed':failed.length?'partial':'success'
  const report:RefreshReport={status,trigger,startedAt,completedAt:new Date().toISOString(),marketDate,sources:{toss:tossStatus,google:googleStatus,supabase:supabaseStatus},marketOverview:overviewStatus(mergedOverview)}
  meta={catalog,marketOverview:mergedOverview,updatedAt:report.completedAt,refreshCycle:refreshCycle(),lastRefresh:report};await saveDashboardMeta(db,meta)
  return{payloads,catalog,marketOverview:mergedOverview,refresh:report}
}

export async function handleScheduledRefresh(db:D1Database,bindings:MarketBindings){return refreshDashboard(db,bindings,'scheduled',false)}

export async function handleMarketData(request:Request,db:D1Database,bindings:SyncBindings={}):Promise<Response>{
  const url=new URL(request.url);await ensureSchema(db)
  if(request.method==='POST'&&url.searchParams.get('sync')==='1')return importTossSync(request,db,bindings)
  if(url.searchParams.get('status')==='1'){const meta=await loadDashboardMeta(db);return Response.json({tossConfigured:Boolean(tossCredentials(bindings)),googleSheetsConfigured:googleConfigured(bindings),supabaseConfigured:supabaseConfigured(bindings),durableStorage:true,lastRefresh:meta.lastRefresh??null,marketOverview:overviewStatus(meta.marketOverview)})}
  if(url.searchParams.get('dashboard')==='1'){
    const force=request.headers.get('x-refresh-market-data')==='1';if(force){const refreshed=await refreshDashboard(db,bindings,'manual',true);await withFundamentalsHistory(db,refreshed.payloads);return response(refreshed,refreshed.refresh.status==='success'?'DASHBOARD-REFRESH':'DASHBOARD-PARTIAL',refreshed.refresh.status==='failed'?502:200)}
    const meta=await loadDashboardMeta(db),entries=await Promise.all(meta.catalog.stocks.filter(stock=>stock.active).map(async stock=>[stock.ticker,await loadStored(db,stock.ticker)] as const)),payloads=Object.fromEntries(entries.filter(([,entry])=>entry.payload).map(([ticker,entry])=>[ticker,storedView(entry.payload!)]));await withFundamentalsHistory(db,payloads);return response({payloads,catalog:meta.catalog,marketOverview:meta.marketOverview,refresh:meta.lastRefresh??null},Object.keys(payloads).length?'D1-DASHBOARD-HIT':'D1-DASHBOARD-EMPTY')
  }
  const symbolsParam=url.searchParams.get('symbols'),symbols=(symbolsParam?symbolsParam.split(','):[url.searchParams.get('symbol')??'']).map(value=>value.trim().toUpperCase()).filter(Boolean)
  if(!symbols.length||symbols.length>20||symbols.some(symbol=>!validSymbol(symbol)))return response({error:'Invalid symbols'},'INVALID',400)
  const entries=Object.fromEntries(await Promise.all(symbols.map(async symbol=>[symbol,await loadStored(db,symbol)] as const))),force=request.headers.get('x-refresh-market-data')==='1'
  if(!force){const payloads=Object.fromEntries(symbols.filter(symbol=>entries[symbol].payload).map(symbol=>[symbol,storedView(entries[symbol].payload!)]));if(symbolsParam)return Object.keys(payloads).length?response({payloads},'D1-HIT'):response({error:'No stored snapshot'},'D1-MISS',503);return payloads[symbols[0]]?response(payloads[symbols[0]],'D1-HIT'):response({error:'No stored snapshot'},'D1-MISS',503)}
  let googleRecords:Record<string,GoogleFinanceRecord>={};if(googleConfigured(bindings))try{googleRecords=await loadGoogleFinanceSheet({spreadsheetId:bindings.GOOGLE_SHEETS_ID!,apiKey:bindings.GOOGLE_SHEETS_API_KEY!,masterRange:bindings.GOOGLE_SHEETS_MASTER_RANGE??'STOCK_MASTER!A1:Z1000',historyRange:'',marketRange:bindings.GOOGLE_SHEETS_MARKET_RANGE})}catch{googleRecords={}}
  const credentials=tossCredentials(bindings),quotes:Record<string,StockQuote>=credentials?await loadTossPrices(symbols.filter(symbol=>symbol!=='SPCX'),credentials).catch(()=>({} as Record<string,StockQuote>)):{},payloads:Record<string,StoredPayload>={}
  for(const symbol of symbols){const entry=entries[symbol],fresh=credentials&&symbol!=='SPCX'?await loadTossDailyPrices(symbol,credentials,entry.payload?.historicalPrices.length?1:5).catch(()=>[]):[],payload=refreshedPayload(symbol,entry.payload,googleRecords[symbol],quotes[symbol],fresh);if(payload){await saveStored(db,symbol,payload,payload.quote?.marketDate??payload.historicalPrices.at(-1)?.date??null);await accumulate(db,bindings,symbol,payload).catch(()=>null);payloads[symbol]=payload}}
  if(symbolsParam)return Object.keys(payloads).length?response({payloads},'REFRESH'):response({error:'Providers unavailable'},'PROVIDER-FAIL',502);return payloads[symbols[0]]?response(payloads[symbols[0]],'REFRESH'):response({error:'Providers unavailable'},'PROVIDER-FAIL',502)
}
