import { evaluateCompanyQuality } from '../src/services/companyQualityAnalysis'
import type { CompanyQualityEvaluation, MetricValue, SecFinancialQuarter } from '../src/types'

type Fact={start?:string;end:string;val:number;accn:string;fy?:number;fp?:string;form:string;filed:string;frame?:string}
type CompanyFacts={cik:number;entityName:string;facts?:{'us-gaap'?:Record<string,{units:Record<string,Fact[]>}>}}
type TickerFile=Record<string,{cik_str:number;ticker:string;title:string}>
type Submission={filings?:{recent?:{accessionNumber?:string[];form?:string[];filingDate?:string[]}}}
type Bindings={SEC_USER_AGENT?:string}

export const SEC_TAGS={
  revenue:['RevenueFromContractWithCustomerExcludingAssessedTax','Revenues','SalesRevenueNet'],operatingIncome:['OperatingIncomeLoss'],netIncome:['NetIncomeLoss','ProfitLoss'],epsBasic:['EarningsPerShareBasic'],epsDiluted:['EarningsPerShareDiluted'],operatingCashFlow:['NetCashProvidedByUsedInOperatingActivities'],capex:['PaymentsToAcquirePropertyPlantAndEquipment','PaymentsToAcquireProductiveAssets','PaymentsForPropertyPlantAndEquipment'],cash:['CashAndCashEquivalentsAtCarryingValue','CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents'],assets:['Assets'],liabilities:['Liabilities'],debtCurrent:['LongTermDebtCurrent','ShortTermBorrowings'],debtNoncurrent:['LongTermDebtNoncurrent'],equity:['StockholdersEquity','StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest'],
} as const
const forms=new Set(['10-Q','10-Q/A','10-K','10-K/A'])
const days=(start:string|undefined,end:string)=>start?Math.round((Date.parse(end)-Date.parse(start))/86400000)+1:0
const latest=(rows:Fact[])=>[...rows].sort((a,b)=>a.filed.localeCompare(b.filed)||a.accn.localeCompare(b.accn)).at(-1)
const factsFor=(data:CompanyFacts,tags:readonly string[],unit:string)=>{const gaap=data.facts?.['us-gaap']??{},result:Fact[]=[],seen=new Set<string>();for(const tag of tags){const units=gaap[tag]?.units;if(!units)continue;const rows=units[unit]??Object.entries(units).find(([key])=>key.toLowerCase()===unit.toLowerCase())?.[1];for(const row of rows??[]){const key=[row.start,row.end,row.fy,row.fp,row.form,row.accn].join('|');if(forms.has(row.form)&&Number.isFinite(row.val)&&!seen.has(key)){seen.add(key);result.push(row)}}}return result}
const direct=(rows:Fact[],fy:number,fp:string)=>latest(rows.filter(row=>row.fy===fy&&row.fp===fp&&days(row.start,row.end)>=60&&days(row.start,row.end)<=130))
const cumulative=(rows:Fact[],fy:number,fp:string,min:number,max:number)=>latest(rows.filter(row=>row.fy===fy&&row.fp===fp&&days(row.start,row.end)>=min&&days(row.start,row.end)<=max))
const annual=(rows:Fact[],fy:number)=>latest(rows.filter(row=>row.fy===fy&&row.fp==='FY'&&days(row.start,row.end)>=320&&days(row.start,row.end)<=410))
const quarterValues=(rows:Fact[],fy:number):Record<'Q1'|'Q2'|'Q3'|'Q4',Fact|undefined>=>{
  const q1=direct(rows,fy,'Q1'),q2Direct=direct(rows,fy,'Q2'),q3Direct=direct(rows,fy,'Q3'),q2Cum=cumulative(rows,fy,'Q2',150,220),q3Cum=cumulative(rows,fy,'Q3',230,320),year=annual(rows,fy)
  const derived=(base:Fact|undefined,subtract:Fact[],fp:'Q2'|'Q3'|'Q4'):Fact|undefined=>base&&subtract.every(Boolean)?{...base,fp,val:base.val-subtract.reduce((sum,item)=>sum+item.val,0)}:undefined
  const q2=q2Direct??derived(q2Cum,q1?[q1]:[],'Q2'),q3=q3Direct??derived(q3Cum,q1&&q2?[q1,q2]:[],'Q3'),q4=year&&q1&&q2&&q3?derived(year,[q1,q2,q3],'Q4'):undefined
  return{Q1:q1,Q2:q2,Q3:q3,Q4:q4}
}
const instantMap=(rows:Fact[])=>{const map=new Map<string,Fact>();for(const row of rows.filter(row=>!row.start)){const previous=map.get(row.end);if(!previous||row.filed>previous.filed)map.set(row.end,row)}return map}
const value=(fact:Fact|undefined):MetricValue=>fact?.val??null
export function normalizeCompanyFacts(ticker:string,cik:string,data:CompanyFacts,asOf=new Date().toISOString().slice(0,10)):SecFinancialQuarter[]{
  const duration={revenue:factsFor(data,SEC_TAGS.revenue,'USD'),operatingIncome:factsFor(data,SEC_TAGS.operatingIncome,'USD'),netIncome:factsFor(data,SEC_TAGS.netIncome,'USD'),epsBasic:factsFor(data,SEC_TAGS.epsBasic,'USD/shares'),epsDiluted:factsFor(data,SEC_TAGS.epsDiluted,'USD/shares'),operatingCashFlow:factsFor(data,SEC_TAGS.operatingCashFlow,'USD'),capex:factsFor(data,SEC_TAGS.capex,'USD')}
  for(const key of Object.keys(duration) as (keyof typeof duration)[])duration[key]=duration[key].filter(row=>row.filed<=asOf)
  const instant={cash:instantMap(factsFor(data,SEC_TAGS.cash,'USD').filter(row=>row.filed<=asOf)),assets:instantMap(factsFor(data,SEC_TAGS.assets,'USD').filter(row=>row.filed<=asOf)),liabilities:instantMap(factsFor(data,SEC_TAGS.liabilities,'USD').filter(row=>row.filed<=asOf)),debtCurrent:instantMap(factsFor(data,SEC_TAGS.debtCurrent,'USD').filter(row=>row.filed<=asOf)),debtNoncurrent:instantMap(factsFor(data,SEC_TAGS.debtNoncurrent,'USD').filter(row=>row.filed<=asOf)),equity:instantMap(factsFor(data,SEC_TAGS.equity,'USD').filter(row=>row.filed<=asOf))}
  const years=[...new Set(Object.values(duration).flat().map(row=>row.fy).filter((fy):fy is number=>typeof fy==='number'))].sort((a,b)=>a-b),series=Object.fromEntries(Object.entries(duration).map(([key,rows])=>[key,Object.fromEntries(years.map(fy=>[fy,quarterValues(rows,fy)]))])) as Record<keyof typeof duration,Record<number,Record<'Q1'|'Q2'|'Q3'|'Q4',Fact|undefined>>>
  const result:SecFinancialQuarter[]=[];for(const fy of years)for(const fiscalQuarter of ['Q1','Q2','Q3','Q4'] as const){const anchors=[series.revenue[fy]?.[fiscalQuarter],series.netIncome[fy]?.[fiscalQuarter],series.epsDiluted[fy]?.[fiscalQuarter]].filter(Boolean) as Fact[];const anchor=latest(anchors);if(!anchor)continue;const periodEnd=anchor.end,ocf=value(series.operatingCashFlow[fy]?.[fiscalQuarter]),capex=value(series.capex[fy]?.[fiscalQuarter]),debtCurrent=value(instant.debtCurrent.get(periodEnd)),debtNoncurrent=value(instant.debtNoncurrent.get(periodEnd));result.push({ticker,cik,fiscalYear:fy,fiscalQuarter,periodEnd,filedAt:anchor.filed,accessionNumber:anchor.accn,revenue:value(series.revenue[fy]?.[fiscalQuarter]),operatingIncome:value(series.operatingIncome[fy]?.[fiscalQuarter]),netIncome:value(series.netIncome[fy]?.[fiscalQuarter]),epsBasic:value(series.epsBasic[fy]?.[fiscalQuarter]),epsDiluted:value(series.epsDiluted[fy]?.[fiscalQuarter]),operatingCashFlow:ocf,capex,freeCashFlow:typeof ocf==='number'&&typeof capex==='number'?ocf-capex:null,cash:value(instant.cash.get(periodEnd)),totalAssets:value(instant.assets.get(periodEnd)),totalLiabilities:value(instant.liabilities.get(periodEnd)),totalDebt:typeof debtCurrent==='number'||typeof debtNoncurrent==='number'?(debtCurrent??0)+(debtNoncurrent??0):null,stockholdersEquity:value(instant.equity.get(periodEnd)),source:'SEC'})}
  return result.sort((a,b)=>a.periodEnd.localeCompare(b.periodEnd)).slice(-16)
}
const headers=(bindings:Bindings)=>({'User-Agent':bindings.SEC_USER_AGENT??'MyStockLog https://im-global-ant.korlove88.chatgpt.site','Accept-Encoding':'gzip, deflate','Accept':'application/json'})
const secJson=async<T>(url:string,bindings:Bindings)=>{const response=await fetch(url,{headers:headers(bindings)});if(!response.ok)throw new Error(`SEC ${response.status}`);return response.json() as Promise<T>}
export const parseTickerCikMap=(data:TickerFile)=>Object.fromEntries(Object.values(data).map(row=>[row.ticker.toUpperCase(),String(row.cik_str).padStart(10,'0')]))
export async function loadTickerCikMap(bindings:Bindings){return parseTickerCikMap(await secJson<TickerFile>('https://www.sec.gov/files/company_tickers.json',bindings))}
const latestFiling=(data:Submission)=>{const recent=data.filings?.recent,forms=recent?.form??[],accessions=recent?.accessionNumber??[],dates=recent?.filingDate??[];for(let index=0;index<forms.length;index++)if(['10-Q','10-Q/A','10-K','10-K/A'].includes(forms[index]))return{accession:accessions[index],filedAt:dates[index]};return null}
export async function refreshSecFinancials(db:D1Database,tickers:string[],bindings:Bindings,maxCompanyFacts=3){
  const mapping=await loadTickerCikMap(bindings);let checked=0,updated=0,missing=0,failed=0
  for(const ticker of tickers){const cik=mapping[ticker];if(!cik){missing++;continue}try{const submission=await secJson<Submission>(`https://data.sec.gov/submissions/CIK${cik}.json`,bindings),filing=latestFiling(submission);checked++;if(!filing){missing++;continue}const state=await db.prepare('SELECT last_accession FROM sec_sync_state WHERE ticker=?1').bind(ticker).first<{last_accession:string}>();if(state?.last_accession===filing.accession||updated>=maxCompanyFacts)continue;const facts=await secJson<CompanyFacts>(`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`,bindings),quarters=normalizeCompanyFacts(ticker,cik,facts);await saveFinancialQuarters(db,quarters);await db.prepare('INSERT INTO sec_sync_state(ticker,cik,last_accession,last_filed_at,checked_at,status,error) VALUES(?1,?2,?3,?4,?5,?6,NULL) ON CONFLICT(ticker) DO UPDATE SET cik=excluded.cik,last_accession=excluded.last_accession,last_filed_at=excluded.last_filed_at,checked_at=excluded.checked_at,status=excluded.status,error=NULL').bind(ticker,cik,filing.accession,filing.filedAt,new Date().toISOString(),'ok').run();updated++}catch(error){failed++;await db.prepare('INSERT INTO sec_sync_state(ticker,cik,checked_at,status,error) VALUES(?1,?2,?3,?4,?5) ON CONFLICT(ticker) DO UPDATE SET checked_at=excluded.checked_at,status=excluded.status,error=excluded.error').bind(ticker,cik,new Date().toISOString(),'failed',error instanceof Error?error.message:'SEC failed').run()}}
  return{checked,updated,missing,failed}
}
async function saveFinancialQuarters(db:D1Database,rows:SecFinancialQuarter[]){const sql='INSERT INTO financial_quarters(ticker,cik,fiscal_year,fiscal_quarter,period_end,filed_at,accession_number,revenue,operating_income,net_income,eps_basic,eps_diluted,operating_cash_flow,capex,free_cash_flow,cash,total_assets,total_liabilities,total_debt,stockholders_equity,source,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19,?20,?21,?22) ON CONFLICT(ticker,period_end) DO UPDATE SET cik=excluded.cik,fiscal_year=excluded.fiscal_year,fiscal_quarter=excluded.fiscal_quarter,filed_at=excluded.filed_at,accession_number=excluded.accession_number,revenue=excluded.revenue,operating_income=excluded.operating_income,net_income=excluded.net_income,eps_basic=excluded.eps_basic,eps_diluted=excluded.eps_diluted,operating_cash_flow=excluded.operating_cash_flow,capex=excluded.capex,free_cash_flow=excluded.free_cash_flow,cash=excluded.cash,total_assets=excluded.total_assets,total_liabilities=excluded.total_liabilities,total_debt=excluded.total_debt,stockholders_equity=excluded.stockholders_equity,source=excluded.source,updated_at=excluded.updated_at WHERE excluded.filed_at>=financial_quarters.filed_at';for(let index=0;index<rows.length;index+=50)await db.batch(rows.slice(index,index+50).map(row=>db.prepare(sql).bind(row.ticker,row.cik,row.fiscalYear,row.fiscalQuarter,row.periodEnd,row.filedAt,row.accessionNumber,row.revenue,row.operatingIncome,row.netIncome,row.epsBasic,row.epsDiluted,row.operatingCashFlow,row.capex,row.freeCashFlow,row.cash,row.totalAssets,row.totalLiabilities,row.totalDebt,row.stockholdersEquity,row.source,new Date().toISOString())))}
export async function loadCompanyQuality(db:D1Database,ticker:string):Promise<{quarters:SecFinancialQuarter[];evaluation:CompanyQualityEvaluation}>{const result=await db.prepare('SELECT * FROM financial_quarters WHERE ticker=?1 ORDER BY period_end ASC').bind(ticker).all<Record<string,unknown>>(),quarters=result.results.map(row=>({ticker:String(row.ticker),cik:String(row.cik),fiscalYear:Number(row.fiscal_year),fiscalQuarter:String(row.fiscal_quarter) as SecFinancialQuarter['fiscalQuarter'],periodEnd:String(row.period_end),filedAt:String(row.filed_at),accessionNumber:String(row.accession_number),revenue:row.revenue as MetricValue,operatingIncome:row.operating_income as MetricValue,netIncome:row.net_income as MetricValue,epsBasic:row.eps_basic as MetricValue,epsDiluted:row.eps_diluted as MetricValue,operatingCashFlow:row.operating_cash_flow as MetricValue,capex:row.capex as MetricValue,freeCashFlow:row.free_cash_flow as MetricValue,cash:row.cash as MetricValue,totalAssets:row.total_assets as MetricValue,totalLiabilities:row.total_liabilities as MetricValue,totalDebt:row.total_debt as MetricValue,stockholdersEquity:row.stockholders_equity as MetricValue,source:'SEC' as const}));return{quarters,evaluation:evaluateCompanyQuality(quarters)}}
