'use client'

import { useEffect, useMemo, useState, useSyncExternalStore } from 'react'
import { ChevronDown, ChevronRight, FileSpreadsheet, Home, KeyRound, Menu, NotebookPen, Pencil, RefreshCw, Save, Search, Settings, Trash2, X } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { referenceSnapshot } from './data/referenceSnapshot'
import { calculateMovingAverageSeries } from './services/metricsCalculator'
import { createStockDataProvider, type DataMode, type ValidationRow } from './services/stockData'
import { createStrategyNotesService, type StrategyNote } from './services/strategyNotes'
import type { HistoricalPrice, MetricValue, StockSnapshot } from './types'

type Page = 'home'|'stock'|'notes'|'settings'
type DetailTab = 'overview'|'trend'|'fundamentals'|'issues'|'ai'
type Period = '1M'|'3M'|'6M'|'1Y'|'3Y'|'5Y'
type SortKey = keyof StockSnapshot | `mdd${number}`
type Column = {key:SortKey;label:string;kind:'text'|'money'|'percent'|'cap'|'number';sticky?:'ticker'|'company'}
type ApiConfig = {fmpKey:string;sheetsKey:string;sheetId:string;supabaseUrl:string;supabaseAnonKey:string;openAiKey:string}
type Connection = 'idle'|'testing'|'ok'|'error'

const emptyConfig:ApiConfig={fmpKey:'',sheetsKey:'',sheetId:'',supabaseUrl:'',supabaseAnonKey:'',openAiKey:''}
const tags=['가격','실적','이슈','리스크','전략']
const periods:Period[]=['1M','3M','6M','1Y','3Y','5Y']
const currentYear=new Date().getUTCFullYear()
const mddYears=[currentYear-2,currentYear-1,currentYear]
const columns:Column[]=[
  {key:'ticker',label:'티커',kind:'text',sticky:'ticker'},{key:'company',label:'종목명',kind:'text',sticky:'company'},{key:'sector',label:'업종',kind:'text'},
  {key:'marketCap',label:'시가총액',kind:'cap'},{key:'pe',label:'PER',kind:'number'},{key:'eps',label:'EPS',kind:'money'},{key:'price',label:'현재가',kind:'money'},
  {key:'changePercent',label:'전일대비',kind:'percent'},{key:'ath',label:'ATH',kind:'money'},{key:'high52',label:'52주 고점',kind:'money'},{key:'drawdown52',label:'52주 고점 대비',kind:'percent'},
  {key:'low52',label:'52주 저점',kind:'money'},{key:'atl',label:'ATL',kind:'money'},...mddYears.map(year=>({key:`mdd${year}` as SortKey,label:`MDD ${year}`,kind:'percent' as const})),
  {key:'yearOpen',label:'연초가',kind:'money'},{key:'ytdReturn',label:'YTD',kind:'percent'},
]
const detailTabs:{key:DetailTab;label:string}[]=[{key:'overview',label:'개요'},{key:'trend',label:'가격·추세'},{key:'fundamentals',label:'기업·실적'},{key:'issues',label:'뉴스·이슈'},{key:'ai',label:'AI 분석'}]
const getValue=(stock:StockSnapshot,key:SortKey):MetricValue|string|null=>key.startsWith('mdd')?stock.mdd[Number(key.slice(3))]:stock[key as keyof StockSnapshot] as MetricValue|string|null
const fmt=(value:MetricValue|string|null,kind:Column['kind'])=>{if(value===null||value===undefined||value==='')return '—';if(typeof value==='string')return value;if(kind==='percent')return `${value>0?'+':''}${(value*100).toFixed(2)}%`;if(kind==='cap')return value>=1e12?`$${(value/1e12).toFixed(2)}T`:value>=1e9?`$${(value/1e9).toFixed(1)}B`:`$${(value/1e6).toFixed(0)}M`;if(kind==='money')return `$${value.toLocaleString('en-US',{maximumFractionDigits:2})}`;return value.toLocaleString('en-US',{maximumFractionDigits:2})}
const tone=(value:MetricValue)=>(value??0)>0?'positive':(value??0)<0?'negative':''
const loadJson=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)??'') as T}catch{return fallback}}
const subscribeHydration=()=>()=>{}
const chartPoints=(history:HistoricalPrice[],width=320,height=90)=>{const values=history.map(p=>p.adjustedClose??p.close).filter(Number.isFinite);if(values.length<2)return'';const min=Math.min(...values),max=Math.max(...values),range=max-min||1;return values.map((value,index)=>`${4+index*(width-8)/(values.length-1)},${height-5-(value-min)*(height-12)/range}`).join(' ')}

function App(){
  const hydrated=useSyncExternalStore(subscribeHydration,()=>true,()=>false)
  const [page,setPage]=useState<Page>('home'),[detailTab,setDetailTab]=useState<DetailTab>('overview')
  const [query,setQuery]=useState(''),[selectedTicker,setSelectedTicker]=useState(referenceSnapshot[0].ticker),[quickTicker,setQuickTicker]=useState<string|null>(null)
  const [sort,setSort]=useState<{key:SortKey;dir:1|-1}>({key:'marketCap',dir:-1}),[mobileNav,setMobileNav]=useState(false)
  const [allStocks,setAllStocks]=useState(referenceSnapshot),[dataMode,setDataMode]=useState<DataMode>('fallback'),[marketDate,setMarketDate]=useState<string|null>(null),[loading,setLoading]=useState(true)
  const [validation,setValidation]=useState<ValidationRow[]>([])
  const [config,setConfig]=useState<ApiConfig>(()=>typeof window==='undefined'?emptyConfig:loadJson('im-ant-api-config',emptyConfig)),[draftConfig,setDraftConfig]=useState<ApiConfig>(()=>typeof window==='undefined'?emptyConfig:loadJson('im-ant-api-config',emptyConfig))
  const [fmpConnection,setFmpConnection]=useState<Connection>('idle'),[supabaseConnection,setSupabaseConnection]=useState<Connection>('idle')
  const [notes,setNotes]=useState<StrategyNote[]>(()=>typeof window==='undefined'?[]:loadJson('im-ant-notes',[])),[noteText,setNoteText]=useState(''),[noteTag,setNoteTag]=useState('전략'),[noteFilter,setNoteFilter]=useState('전체')
  const [authEmail,setAuthEmail]=useState(''),[authPassword,setAuthPassword]=useState(''),[authUser,setAuthUser]=useState<string|null>(null),[noteMessage,setNoteMessage]=useState('')
  const notesService=useMemo(()=>createStrategyNotesService(config.supabaseUrl,config.supabaseAnonKey),[config.supabaseUrl,config.supabaseAnonKey])

  useEffect(()=>{let active=true;createStockDataProvider(config.fmpKey).getStocks().then(result=>{if(active){setAllStocks(result.stocks);setDataMode(result.mode);setMarketDate(result.marketDate);setValidation(result.validation);setFmpConnection(result.mode==='market'?'ok':config.fmpKey?'error':'idle');setLoading(false)}});return()=>{active=false}},[config.fmpKey])
  useEffect(()=>{if(!notesService)return;let active=true;notesService.user().then(async user=>{if(!active)return;if(!user){setSupabaseConnection('idle');setAuthUser(null);return}setAuthUser(user.email??user.id);const remote=await notesService.list();if(!active)return;const migrated=localStorage.getItem('im-ant-notes-migrated')==='1';const localNotes=loadJson<StrategyNote[]>('im-ant-notes',[]);if(!migrated&&localNotes.length){await notesService.migrate(localNotes);localStorage.setItem('im-ant-notes-migrated','1');localStorage.removeItem('im-ant-notes');setNotes(await notesService.list())}else setNotes(remote);setSupabaseConnection('ok')}).catch(()=>{if(active)setSupabaseConnection('error')});return()=>{active=false}},[notesService])

  const selected=allStocks.find(s=>s.ticker===selectedTicker)??allStocks[0],quick=allStocks.find(s=>s.ticker===quickTicker)??null
  const stocks=useMemo(()=>allStocks.filter(s=>`${s.ticker} ${s.company} ${s.sector??''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const av=getValue(a,sort.key),bv=getValue(b,sort.key);if(av==null)return 1;if(bv==null)return-1;return(typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv)))*sort.dir}),[allStocks,query,sort])
  const navigate=(next:Page)=>{setPage(next);setMobileNav(false);setQuickTicker(null)}
  const openDetail=(ticker:string)=>{setSelectedTicker(ticker);setDetailTab('overview');navigate('stock')}
  const saveConfig=async()=>{localStorage.setItem('im-ant-api-config',JSON.stringify(draftConfig));setLoading(true);setConfig({...draftConfig});setFmpConnection(draftConfig.fmpKey?'testing':'idle');setSupabaseConnection(draftConfig.supabaseUrl&&draftConfig.supabaseAnonKey?'testing':'idle')}
  const addNote=async()=>{if(!noteText.trim())return;if(!notesService||!authUser){setNoteMessage('Supabase 로그인 후 저장할 수 있습니다.');return}try{const created=await notesService.create({ticker:selected.ticker,content:noteText.trim(),tag:noteTag});setNotes(prev=>[created,...prev]);setNoteText('');setNoteMessage('저장됨')}catch{setNoteMessage('저장 실패 · RLS와 테이블을 확인하세요')}}
  const removeNote=async(id:string)=>{if(!notesService)return;try{await notesService.remove(id);setNotes(prev=>prev.filter(n=>n.id!==id))}catch{setNoteMessage('삭제 실패')}}
  const updateNote=async(id:string,content:string,tag:string)=>{if(!notesService)return;try{const updated=await notesService.update(id,{content,tag});setNotes(prev=>prev.map(n=>n.id===id?updated:n))}catch{setNoteMessage('수정 실패')}}
  const authenticate=async(mode:'signin'|'signup')=>{const service=createStrategyNotesService(draftConfig.supabaseUrl,draftConfig.supabaseAnonKey);if(!service){setNoteMessage('Supabase URL과 anon key를 먼저 입력하세요.');return}setSupabaseConnection('testing');try{const user=mode==='signin'?await service.signIn(authEmail,authPassword):await service.signUp(authEmail,authPassword);setAuthUser(user?.email??null);setSupabaseConnection(user?'ok':'idle');setConfig({...draftConfig});localStorage.setItem('im-ant-api-config',JSON.stringify(draftConfig));setNoteMessage(user?'Supabase 연결됨':'이메일 확인 후 로그인하세요.')}catch{setSupabaseConnection('error');setNoteMessage('인증 실패')}}
  const signOut=async()=>{await notesService?.signOut();setAuthUser(null);setSupabaseConnection('idle');setNotes([])}
  const visibleNotes=notes.filter(n=>noteFilter==='전체'||n.ticker===noteFilter||n.tag===noteFilter)
  const validationCounts={ok:validation.filter(v=>v.status==='ok').length,partial:validation.filter(v=>v.status==='partial').length,failed:validation.filter(v=>v.status==='failed').length}

  if(!hydrated)return <div className="app-loading">IM GLOBAL ANT</div>

  return <div className="app-shell"><aside className={mobileNav?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark">A</div><div><strong>IM GLOBAL</strong><span>ANT</span></div><button aria-label="메뉴 닫기" className="mobile-close" onClick={()=>setMobileNav(false)}><X/></button></div><nav>{([['home','홈',Home],['stock','개별종목',FileSpreadsheet],['notes','전략노트',NotebookPen],['settings','설정',Settings]] as const).map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>navigate(key)}><Icon/>{label}</button>)}</nav><div className="sidebar-foot"><span>V1 · 개인 투자 대시보드</span><small>정보 비교용 · 투자 권유 아님</small></div></aside>
    <main><header><button aria-label="메뉴 열기" className="menu-button" onClick={()=>setMobileNav(true)}><Menu/></button><h1>{page==='home'?'관심종목 비교':page==='stock'?'개별종목':page==='notes'?'전략노트':'설정'}</h1><div className={`connection-pill ${dataMode}`}>{loading?'데이터 확인 중':dataMode==='market'?`FMP 연결 · ${marketDate??'최근 종가'}`:'Reference 데이터'}</div></header>
      {page==='home'&&<HomePage stocks={stocks} allCount={allStocks.length} query={query} setQuery={setQuery} sort={sort} sortBy={key=>setSort(p=>({key,dir:p.key===key?p.dir===1?-1:1:1}))} onQuick={setQuickTicker} validation={validationCounts}/>} 
      {page==='stock'&&selected&&<StockPage stock={selected} stocks={allStocks} detailTab={detailTab} setDetailTab={setDetailTab} selectTicker={setSelectedTicker} noteText={noteText} setNoteText={setNoteText} noteTag={noteTag} setNoteTag={setNoteTag} addNote={addNote} noteMessage={noteMessage}/>} 
      {page==='notes'&&<NotesPage notes={visibleNotes} allNotes={notes} filter={noteFilter} setFilter={setNoteFilter} remove={removeNote} update={updateNote} connected={supabaseConnection==='ok'}/>} 
      {page==='settings'&&<SettingsPage config={draftConfig} setConfig={setDraftConfig} save={saveConfig} fmp={fmpConnection} supabase={supabaseConnection} stocks={allStocks} email={authEmail} setEmail={setAuthEmail} password={authPassword} setPassword={setAuthPassword} authUser={authUser} authenticate={authenticate} signOut={signOut} message={noteMessage}/>} 
    </main>{quick&&<><button aria-label="Quick View 닫기" className="scrim" onClick={()=>setQuickTicker(null)}/><QuickView stock={quick} close={()=>setQuickTicker(null)} detail={()=>openDetail(quick.ticker)}/></>}</div>
}

function HomePage({stocks,allCount,query,setQuery,sort,sortBy,onQuick,validation}:{stocks:StockSnapshot[];allCount:number;query:string;setQuery:(v:string)=>void;sort:{key:SortKey;dir:1|-1};sortBy:(k:SortKey)=>void;onQuick:(t:string)=>void;validation:{ok:number;partial:number;failed:number}}){return <><section className="toolbar"><label><Search/><input aria-label="종목 검색" placeholder="티커, 종목명, 업종 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="validation-summary">{validation.ok+validation.partial+validation.failed>0&&`${allCount} checked · ${validation.ok} OK · ${validation.partial} partial · ${validation.failed} failed`}</div><div className="count"><strong>{stocks.length}</strong><span>/ {allCount} 종목</span></div></section><section className="desktop-table"><table><thead><tr>{columns.map(c=><th key={c.key} className={c.sticky?`sticky ${c.sticky}`:''}><button onClick={()=>sortBy(c.key)}>{c.label}<ChevronDown className={sort.key===c.key?(sort.dir===-1?'sorted desc':'sorted'):''}/></button></th>)}</tr></thead><tbody>{stocks.map(s=><tr key={s.ticker} onClick={()=>onQuick(s.ticker)}>{columns.map(c=>{const v=getValue(s,c.key);return <td key={c.key} className={`${c.sticky?`sticky ${c.sticky}`:''} ${c.kind==='percent'&&typeof v==='number'?tone(v):''}`}>{c.key==='ticker'?<><span className="ticker-logo">{s.ticker[0]}</span><strong>{s.ticker}</strong><i className={`source-dot ${s.dataSource}`}/></>:fmt(v,c.kind)}</td>})}</tr>)}</tbody></table></section><section className="mobile-cards">{stocks.map(s=><button key={s.ticker} onClick={()=>onQuick(s.ticker)}><div><span className="ticker-logo">{s.ticker[0]}</span><div><strong>{s.ticker}</strong><small>{s.company}</small></div><ChevronRight/></div><div className="mobile-metrics"><span>현재가<strong>{fmt(s.price,'money')}</strong></span><span>전일대비<strong className={tone(s.changePercent)}>{fmt(s.changePercent,'percent')}</strong></span><span>52주 고점 대비<strong className="negative">{fmt(s.drawdown52,'percent')}</strong></span><span>YTD<strong className={tone(s.ytdReturn)}>{fmt(s.ytdReturn,'percent')}</strong></span></div></button>)}</section></>}

function StockPage({stock,stocks,detailTab,setDetailTab,selectTicker,noteText,setNoteText,noteTag,setNoteTag,addNote,noteMessage}:{stock:StockSnapshot;stocks:StockSnapshot[];detailTab:DetailTab;setDetailTab:(v:DetailTab)=>void;selectTicker:(v:string)=>void;noteText:string;setNoteText:(v:string)=>void;noteTag:string;setNoteTag:(v:string)=>void;addNote:()=>void;noteMessage:string}){return <div className="page-wrap"><section className="stock-head"><div><select aria-label="종목 선택" value={stock.ticker} onChange={e=>selectTicker(e.target.value)}>{stocks.map(s=><option key={s.ticker}>{s.ticker}</option>)}</select><h2>{stock.company}</h2><p>{stock.sector??'업종 미분류'} · {stock.dataSource==='fmp'?'FMP':'Reference'}</p></div><div className="headline-price"><strong>{fmt(stock.price,'money')}</strong><span className={tone(stock.changePercent)}>{fmt(stock.changePercent,'percent')}</span></div></section><nav className="subtabs">{detailTabs.map(tab=><button key={tab.key} className={detailTab===tab.key?'active':''} onClick={()=>setDetailTab(tab.key)}>{tab.label}</button>)}</nav><div className="detail-layout"><section className="detail-content">{detailTab==='overview'&&<MetricGrid stock={stock}/>} {detailTab==='trend'&&<PriceTrend stock={stock}/>} {detailTab==='fundamentals'&&<div className="info-panel"><h3>기업·실적</h3><div className="fundamental-list"><span>시가총액<strong>{fmt(stock.marketCap,'cap')}</strong></span><span>PER<strong>{fmt(stock.pe,'number')}</strong></span><span>EPS<strong>{fmt(stock.eps,'money')}</strong></span><span>매출 / 순이익<strong>—</strong></span></div></div>} {detailTab==='issues'&&<Empty title="핵심 이슈 데이터 준비 중"/>} {detailTab==='ai'&&<Empty title="AI 분석 연결 준비 완료"/>}</section><aside className="note-composer"><h3>전략노트</h3><p>{stock.ticker}</p><textarea aria-label="전략노트 내용" value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="다음 실적에서 확인할 내용을 기록하세요"/><div><select aria-label="전략노트 태그" value={noteTag} onChange={e=>setNoteTag(e.target.value)}>{tags.map(t=><option key={t}>{t}</option>)}</select><button onClick={addNote}><Save/>저장</button></div>{noteMessage&&<small>{noteMessage}</small>}</aside></div></div>}

function PriceTrend({stock}:{stock:StockSnapshot}){const [period,setPeriod]=useState<Period>('1Y');const [visible,setVisible]=useState({ma20:true,ma60:true,ma120:false,ma200:true});const series=useMemo(()=>calculateMovingAverageSeries(stock.priceHistory),[stock.priceHistory]);const data=useMemo(()=>{if(!series.length)return[];const latest=new Date(`${series.at(-1)!.date}T00:00:00Z`);const amount=Number(period.slice(0,-1)),unit=period.at(-1);const start=new Date(latest);if(unit==='M')start.setUTCMonth(start.getUTCMonth()-amount);else start.setUTCFullYear(start.getUTCFullYear()-amount);const iso=start.toISOString().slice(0,10);return series.filter(p=>p.date>=iso)},[series,period]);const colors={ma20:'#61d6a1',ma60:'#77a7ff',ma120:'#c58cff',ma200:'#ff8a65'};return <><div className="chart-card"><div className="chart-toolbar"><div className="period-buttons">{periods.map(p=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div><div className="ma-toggles">{(['ma20','ma60','ma120','ma200'] as const).map(key=><button key={key} className={visible[key]?'active':''} onClick={()=>setVisible(v=>({...v,[key]:!v[key]}))}>{key.toUpperCase()}</button>)}</div></div>{data.length>1?<div className="chart-canvas"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:12,right:8,left:0,bottom:4}}><CartesianGrid stroke="#202b38" vertical={false}/><XAxis dataKey="date" minTickGap={45} tick={{fill:'#778493',fontSize:9}} tickFormatter={v=>String(v).slice(5)}/><YAxis domain={['auto','auto']} width={52} tick={{fill:'#778493',fontSize:9}} tickFormatter={v=>`$${Number(v).toFixed(0)}`}/><Tooltip contentStyle={{background:'#0d141d',border:'1px solid #293543',borderRadius:8,fontSize:11}} labelFormatter={v=>String(v)} formatter={(v,name)=>[`$${Number(v).toFixed(2)}`,String(name).toUpperCase()]}/><Line dataKey="price" name="Price" stroke="#f4c45e" dot={false} strokeWidth={2} connectNulls={false}/>{(['ma20','ma60','ma120','ma200'] as const).map(key=>visible[key]?<Line key={key} dataKey={key} name={key} stroke={colors[key]} dot={false} strokeWidth={1.4} connectNulls={false}/>:null)}</LineChart></ResponsiveContainer></div>:<Empty title="해당 기간 가격 데이터가 없습니다"/>}</div><Returns stock={stock}/></>}

function Returns({stock}:{stock:StockSnapshot}){return <div className="returns-row">{[['1M',stock.return1m],['3M',stock.return3m],['6M',stock.return6m],['YTD',stock.ytdReturn],['1Y',stock.return1y],['3Y',stock.return3y],['5Y',stock.return5y]].map(([label,value])=><span key={String(label)}>{label}<strong className={tone(value as MetricValue)}>{fmt(value as MetricValue,'percent')}</strong></span>)}</div>}
function MetricGrid({stock}:{stock:StockSnapshot}){const items:[string,MetricValue,Column['kind']][]=[['현재가',stock.price,'money'],['전일대비',stock.changePercent,'percent'],['시가총액',stock.marketCap,'cap'],['PER',stock.pe,'number'],['EPS',stock.eps,'money'],['52주 고점',stock.high52,'money'],['52주 저점',stock.low52,'money'],['52주 고점 대비',stock.drawdown52,'percent'],['ATH',stock.ath,'money'],['ATL',stock.atl,'money'],...mddYears.map(year=>[`MDD ${year}`,stock.mdd[year],'percent'] as [string,MetricValue,Column['kind']]),['YTD',stock.ytdReturn,'percent'],['3개월',stock.return3m,'percent'],['1년',stock.return1y,'percent'],['3년',stock.return3y,'percent'],['5년',stock.return5y,'percent']];return <div className="metric-grid">{items.map(([label,value,kind])=><span key={label}>{label}<strong className={kind==='percent'?tone(value):''}>{fmt(value,kind)}</strong></span>)}</div>}

function NotesPage({notes,allNotes,filter,setFilter,remove,update,connected}:{notes:StrategyNote[];allNotes:StrategyNote[];filter:string;setFilter:(v:string)=>void;remove:(id:string)=>void;update:(id:string,content:string,tag:string)=>void;connected:boolean}){const [editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState(''),[draftTag,setDraftTag]=useState('전략');const filters=['전체',...Array.from(new Set(allNotes.flatMap(n=>[n.ticker,n.tag])))];return <div className="page-wrap"><div className="section-head"><div><h2>모든 판단 메모</h2><p>{connected?'Supabase 동기화':'Supabase 로그인 필요'}</p></div><select aria-label="전략노트 필터" value={filter} onChange={e=>setFilter(e.target.value)}>{filters.map(f=><option key={f}>{f}</option>)}</select></div>{notes.length?<section className="notes-board">{notes.map(note=><article key={note.id}><div><strong>{note.ticker}</strong><time>{new Date(note.createdAt).toLocaleDateString('ko-KR',{month:'2-digit',day:'2-digit'})}</time><button aria-label="메모 수정" onClick={()=>{setEditing(note.id);setDraft(note.content);setDraftTag(note.tag)}}><Pencil/></button><button aria-label="메모 삭제" onClick={()=>remove(note.id)}><Trash2/></button></div>{editing===note.id?<><textarea value={draft} onChange={e=>setDraft(e.target.value)}/><select value={draftTag} onChange={e=>setDraftTag(e.target.value)}>{tags.map(t=><option key={t}>{t}</option>)}</select><button className="note-save" onClick={()=>{update(note.id,draft,draftTag);setEditing(null)}}>저장</button></>:<><p>{note.content}</p><span>#{note.tag}</span></>}</article>)}</section>:<Empty title={connected?'아직 기록된 전략노트가 없습니다':'Supabase 로그인 후 전략노트를 사용할 수 있습니다'}/>}</div>}

function SettingsPage({config,setConfig,save,fmp,supabase,stocks,email,setEmail,password,setPassword,authUser,authenticate,signOut,message}:{config:ApiConfig;setConfig:(v:ApiConfig)=>void;save:()=>void;fmp:Connection;supabase:Connection;stocks:StockSnapshot[];email:string;setEmail:(v:string)=>void;password:string;setPassword:(v:string)=>void;authUser:string|null;authenticate:(m:'signin'|'signup')=>void;signOut:()=>void;message:string}){const field=(key:keyof ApiConfig,label:string,placeholder:string,secret=false)=><label><span>{label}</span><input type={secret?'password':'text'} value={config[key]} placeholder={placeholder} autoComplete="off" onChange={e=>setConfig({...config,[key]:e.target.value})}/></label>;const status=(v:Connection)=>v==='testing'?'확인 중':v==='ok'?'연결됨':v==='error'?'연결 실패':'미설정';return <div className="page-wrap settings-page"><section className="settings-intro"><KeyRound/><div><h2>데이터 연결</h2></div></section><section className="settings-card"><div className="settings-title"><div><h3>Financial Modeling Prep</h3></div><span className={`status ${fmp}`}>{status(fmp)}</span></div>{field('fmpKey','FMP API Key','FMP에서 발급받은 키',true)}</section><section className="settings-card"><div className="settings-title"><div><h3>Supabase</h3></div><span className={`status ${supabase}`}>{status(supabase)}</span></div><div className="form-grid">{field('supabaseUrl','Project URL','https://….supabase.co')}{field('supabaseAnonKey','Anon Key','Supabase anon key',true)}</div><div className="auth-form">{authUser?<><span>{authUser}</span><button onClick={signOut}>로그아웃</button></>:<><input aria-label="Supabase 이메일" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="이메일"/><input aria-label="Supabase 비밀번호" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="비밀번호"/><button onClick={()=>authenticate('signin')}>로그인</button><button onClick={()=>authenticate('signup')}>가입</button></>}</div>{message&&<small className="settings-message">{message}</small>}</section><section className="settings-card"><div className="settings-title"><div><h3>Google Sheets</h3></div><span className="status planned">보류</span></div></section><section className="settings-card"><div className="settings-title"><div><h3>OpenAI</h3></div><span className="status planned">연결 준비</span></div>{field('openAiKey','OpenAI API Key','sk-…',true)}</section><section className="watchlist-card"><div><h3>현재 관심종목</h3><p>{stocks.length}개 종목</p></div><div>{stocks.map(stock=><span key={stock.ticker}>{stock.ticker}</span>)}</div></section><button className="save-settings" onClick={save}><RefreshCw/>설정 저장 및 연결 확인</button></div>}

function Empty({title}:{title:string}){return <div className="empty-state"><div>ANT</div><h3>{title}</h3></div>}
function QuickView({stock,close,detail}:{stock:StockSnapshot;close:()=>void;detail:()=>void}){return <aside className="quick-view"><button aria-label="닫기" className="quick-close" onClick={close}><X/></button><p className="eyebrow">QUICK VIEW · {stock.dataSource==='fmp'?'FMP':'REFERENCE'}</p><div className="quick-title"><span className="ticker-logo large">{stock.ticker[0]}</span><div><h2>{stock.ticker}</h2><p>{stock.company} · {stock.sector??'업종 미분류'}</p></div></div><div className="quick-price"><span>현재가</span><strong>{fmt(stock.price,'money')}</strong><em className={tone(stock.changePercent)}>{fmt(stock.changePercent,'percent')}</em></div><div className="spark-placeholder"><svg viewBox="0 0 320 90"><polyline points={chartPoints(stock.priceHistory.slice(-90))}/></svg></div><div className="quick-grid"><span>ATH<strong>{fmt(stock.ath,'money')}</strong></span><span>52주 고점 대비<strong className="negative">{fmt(stock.drawdown52,'percent')}</strong></span><span>YTD<strong className={tone(stock.ytdReturn)}>{fmt(stock.ytdReturn,'percent')}</strong></span><span>3개월<strong>{fmt(stock.return3m,'percent')}</strong></span><span>1년<strong>{fmt(stock.return1y,'percent')}</strong></span><span>3년 / 5년<strong>{fmt(stock.return3y,'percent')} / {fmt(stock.return5y,'percent')}</strong></span></div><button className="detail-button" onClick={detail}>상세분석 보기 <ChevronRight/></button></aside>}

export default App
